'use strict'
const assert=require('assert')
const {pivotObserveCommand}=require('./xlsx-pivot-observer.cjs')
const agent=require('./xlsx-agent-pivot-task.cjs')
let failed=0
async function check(name,fn){try{await fn();console.log('OK '+name)}catch(e){failed++;console.error('FAIL '+name+'\n'+(e?.stack||e))}}
function fixture(){
 const state={pivots:[],sheets:new Set(['Source']),names:new Map(),writes:0,visibleData:{'East|A':10,'West|B':20},pendingData:null,buildOrder:[]}
 function makePivot(source,parent='PivotSheet1'){const sourceSheet=source.sheet||String(source.address).match(/^'([^']+)'!/)?.[1]||'Source',s={name:'Pivot1',source:source.address,sourceSheet,parent,rows:[],cols:[],data:[],style:'PivotStyleLight16'};const p={GetName:()=>s.name,SetName:v=>{s.name=v},GetSource:()=>({GetAddress:()=>s.source,GetWorksheet:()=>({GetName:()=>s.sourceSheet})}),GetParent:()=>({GetName:()=>s.parent}),GetRowFields:()=>s.rows,GetColumnFields:()=>s.cols,GetDataFields:()=>s.data,GetStyleName:()=>s.style,AddFields:x=>{state.buildOrder.push('fields');s.rows.push(x.rows);s.cols.push(x.columns)},AddDataField:x=>{state.buildOrder.push('data');s.data.push(x);if(state.simulateAddDataFieldWrapperBug)throw new TypeError("Cannot read properties of null (reading 'length')")},MoveField:()=>{throw new Error('MoveField fallback must not run')},SetStyleName:x=>{s.style=x},GetData:items=>state.visibleData[items.join('|')],RefreshTable:()=>{if(state.pendingData){state.visibleData=state.pendingData;state.pendingData=null}}};state.pivots.push(p);state.sheets.add(s.parent);return p}
 const api={GetPivotByName:n=>{const p=state.pivots.find(x=>x.GetName()===n);if(!p)throw new Error('missing');return p},GetAllPivotTables:()=>state.pivots,GetDefName:n=>{const refersTo=state.names.get(n);return refersTo?{GetName:()=>n,GetRefersTo:()=>refersTo}:null},GetSheet:n=>state.sheets.has(n)?{GetRange:a=>({address:a,sheet:n}),Delete(){state.writes++;state.sheets.delete(n);state.pivots=state.pivots.filter(p=>p.GetParent().GetName()!==n)}}:null,AddSheet:n=>{state.writes++;state.sheets.add(n)},GetRange:q=>{state.qualifiedSource=q;return {address:q}},InsertPivotNewWorksheet:source=>{state.writes++;return makePivot(source)},InsertPivotExistingWorksheet:(source,destination)=>{state.writes++;state.destination=destination.address;return makePivot(source,destination.sheet)}}
 return {state,api,makePivot}
}
function createSpec(extra={}){return {intent:'create_pivot',name:'EURO_P',sourceSheet:'Source',sourceRange:'A1:C5',rowField:'Region',columnField:'Style',dataField:'Price',styleName:'PivotStyleMedium2',assertions:[{items:['East','A'],expected:'10'},{items:['West','B'],expected:'20'}],...extra}}
function withApi(f,fn){const old=global.Api;global.Api=f.api;try{return fn()}finally{if(old===undefined)delete global.Api;else global.Api=old}}
;(async()=>{
 await check('observer creates complete pivot and verifies GetData assertions',async()=>{const f=fixture(),r=withApi(f,()=>pivotObserveCommand({...createSpec(),apply:true}));assert.equal(r.ok,true);assert.equal(r.state.styleName,'PivotStyleMedium2');assert.equal(r.state.assertions.every(x=>x.value===x.expected),true);assert.equal(f.state.writes,1);assert.equal(f.state.qualifiedSource,"'Source'!$A$1:$C$5")})
 await check('observer creates on an existing identity-matched worksheet in public API field order',async()=>{const f=fixture();f.state.sheets.add('PivotDest');const r=withApi(f,()=>pivotObserveCommand({...createSpec({pivotSheet:'PivotDest',destinationRange:'A1'}),apply:true}));assert.equal(r.ok,true);assert.equal(r.state.parentSheet,'PivotDest');assert.equal(f.state.destination,'A1');assert.deepEqual(f.state.buildOrder,['fields','data'])})
 await check('observer tolerates only the measured AddDataField post-mutation wrapper defect',async()=>{const f=fixture();f.state.sheets.add('PivotDest');f.state.simulateAddDataFieldWrapperBug=true;const r=withApi(f,()=>pivotObserveCommand({...createSpec({pivotSheet:'PivotDest',destinationRange:'A1'}),apply:true}));assert.equal(r.ok,true);assert.equal(r.state.dataFields,1);assert.deepEqual(f.state.buildOrder,['fields','data'])})
 await check('observer rejects unrelated AddDataField errors',async()=>{const f=fixture();f.state.sheets.add('PivotDest');const original=f.api.InsertPivotExistingWorksheet;f.api.InsertPivotExistingWorksheet=(source,destination)=>{const p=original(source,destination);p.AddDataField=()=>{throw new Error('unrelated failure')};return p};const r=withApi(f,()=>pivotObserveCommand({...createSpec({pivotSheet:'PivotDest',destinationRange:'A1'}),apply:true}));assert.equal(r.ok,false);assert.equal(r.stage,'add-data-field');assert.equal(r.error,'unrelated failure')})
 await check('observer repairs only an identity-matched incomplete pivot on an explicit dedicated sheet',async()=>{const f=fixture();f.state.sheets.add('PivotDest');const stale=f.makePivot({address:"'Source'!$A$1:$C$5"},'PivotDest');stale.SetName('EURO_P');stale.AddFields({rows:'Region',columns:'Style'});f.state.buildOrder=[];const r=withApi(f,()=>pivotObserveCommand({...createSpec({pivotSheet:'PivotDest',destinationRange:'A1',repairIncompletePivot:true}),apply:true}));assert.equal(r.ok,true);assert.equal(r.state.parentSheet,'PivotDest');assert.deepEqual(f.state.buildOrder,['fields','data']);assert.equal(f.state.pivots.length,1);assert.equal(f.state.writes,3)})
 await check('observer refuses repair when source identity differs or destination sheet is shared',async()=>{const wrong=fixture();wrong.state.sheets.add('PivotDest');const stale=wrong.makePivot({address:"'Other'!$A$1:$C$5"},'PivotDest');stale.SetName('EURO_P');let r=withApi(wrong,()=>pivotObserveCommand({...createSpec({pivotSheet:'PivotDest',destinationRange:'A1',repairIncompletePivot:true}),apply:true}));assert.equal(r.outcome,'pivot-name-conflict');assert.equal(wrong.state.writes,0);const shared=fixture();shared.state.sheets.add('PivotDest');const target=shared.makePivot({address:"'Source'!$A$1:$C$5"},'PivotDest');target.SetName('EURO_P');const other=shared.makePivot({address:"'Source'!$A$1:$C$5"},'PivotDest');other.SetName('OTHER');r=withApi(shared,()=>pivotObserveCommand({...createSpec({pivotSheet:'PivotDest',destinationRange:'A1',repairIncompletePivot:true}),apply:true}));assert.equal(r.outcome,'pivot-repair-sheet-not-dedicated');assert.equal(shared.state.writes,0)})
 await check('observer recognizes exact pivot no-op',async()=>{const f=fixture();withApi(f,()=>pivotObserveCommand({...createSpec(),apply:true}));const r=withApi(f,()=>pivotObserveCommand({...createSpec(),apply:false}));assert.equal(r.noOp,true)})
 await check('observer uses an exact durable source marker only when reopened GetSource is unavailable',async()=>{const f=fixture(),spec=createSpec({sourceIdentityName:'EURO_P_SOURCE'});f.state.names.set('EURO_P_SOURCE','=Source!$A$1:$C$5');withApi(f,()=>pivotObserveCommand({...spec,apply:true}));f.state.pivots[0].GetSource=()=>{throw new TypeError("Cannot read properties of undefined (reading 'ws')")};let r=withApi(f,()=>pivotObserveCommand({...spec,apply:false}));assert.equal(r.ok,true);assert.equal(r.noOp,true);assert.equal(r.state.sourceProof,'defined-name-fallback');f.state.names.set('EURO_P_SOURCE','=Source!$A$1:$B$5');r=withApi(f,()=>pivotObserveCommand({...spec,apply:false}));assert.equal(r.ok,false);assert.equal(r.state.reason,'pivot-source-marker-mismatch')})
 await check('observer refreshes stale pivot and recognizes retry',async()=>{const f=fixture();withApi(f,()=>pivotObserveCommand({...createSpec(),apply:true}));f.state.pendingData={'East|A':15,'West|B':20};const spec={...createSpec({intent:'refresh_pivot',assertions:[{items:['East','A'],expected:'15'},{items:['West','B'],expected:'20'}]})};const r=withApi(f,()=>pivotObserveCommand({...spec,apply:true}));assert.equal(r.ok,true);assert.equal(r.noOp,false);const retry=withApi(f,()=>pivotObserveCommand({...spec,apply:false}));assert.equal(retry.noOp,true)})
 await check('observer rejects refresh when pivot identity differs',async()=>{const f=fixture();withApi(f,()=>pivotObserveCommand({...createSpec(),apply:true}));const r=withApi(f,()=>pivotObserveCommand({...createSpec({intent:'refresh_pivot',styleName:'PivotStyleMedium3'}),apply:true}));assert.equal(r.outcome,'pivot-refresh-identity-conflict')})
 await check('observer rejects same-name semantic conflict',async()=>{const f=fixture();withApi(f,()=>pivotObserveCommand({...createSpec(),apply:true}));const r=withApi(f,()=>pivotObserveCommand({...createSpec({styleName:'PivotStyleMedium3'}),apply:true}));assert.equal(r.outcome,'pivot-name-conflict')})
 await check('observer deletes only identity-matched pivot sheet',async()=>{const f=fixture();const made=withApi(f,()=>pivotObserveCommand({...createSpec(),apply:true}));const sheet=made.state.parentSheet;const r=withApi(f,()=>pivotObserveCommand({intent:'delete_pivot_sheet',name:'EURO_P',pivotSheet:sheet,apply:true}));assert.equal(r.ok,true);assert.equal(r.state.pivot.present,false);assert.equal(r.state.pivotSheetPresent,false)})
 await check('observer rejects wrong pivot sheet',async()=>{const f=fixture();withApi(f,()=>pivotObserveCommand({...createSpec(),apply:true}));f.state.sheets.add('Other');const r=withApi(f,()=>pivotObserveCommand({intent:'delete_pivot_sheet',name:'EURO_P',pivotSheet:'Other',apply:true}));assert.equal(r.outcome,'pivot-delete-identity-conflict')})
 await check('planner validates deterministic existing-sheet destination and explicit repair policy',async()=>{assert.equal(agent.planTask({operations:[createSpec({pivotSheet:'PivotDest',destinationRange:'A1',repairIncompletePivot:true})]}).operation.repairIncompletePivot,true);for(const bad of [{pivotSheet:'PivotDest'},{destinationRange:'A1'},{pivotSheet:'Source',destinationRange:'A1'},{pivotSheet:'PivotDest',destinationRange:'A1:B2'},{repairIncompletePivot:true},{pivotSheet:'PivotDest',destinationRange:'A1',repairIncompletePivot:false}])assert.equal(agent.planTask({operations:[createSpec(bad)]}).ok,false)})
 await check('planner requires semantic assertions',async()=>{assert.equal(agent.planTask({operations:[{...createSpec(),assertions:[]}]}).ok,false)})
 await check('planner accepts refresh with complete final-state fingerprint',async()=>{const r=agent.planTask({operations:[createSpec({intent:'refresh_pivot'})]});assert.equal(r.ok,true);assert.equal(r.operation.intent,'refresh_pivot')})
 await check('planner preserves only a valid optional pivot source identity name',async()=>{assert.equal(agent.planTask({operations:[createSpec({sourceIdentityName:'EURO_P_SOURCE'})]}).operation.sourceIdentityName,'EURO_P_SOURCE');assert.equal(agent.planTask({operations:[createSpec({sourceIdentityName:'bad name'})]}).ok,false)})
 await check('executor applies then whole-verifies',async()=>{let phase=0,writes=0;const absent={ok:true,source:'live-coedit-editor',noOp:false,state:{measurable:true,present:false,name:'P'},verification:{measurable:true,match:false}},set={ok:true,source:'live-coedit-editor',noOp:true,state:{measurable:true,present:true,name:'P',parentSheet:'Pivot1'},verification:{measurable:true,match:true}};const api={inspect:async()=>({ok:true,authority:'LIVE_READ',sheets:[{name:'Source'}]}),pivotObserved:async(_op,apply)=>{if(apply){phase=1;writes++;return {...set,noOp:false,applied:true}}return phase?set:absent}};const r=await agent.executePivotTask({task:{operations:[{...createSpec(),name:'P'}]},api});assert.equal(r.ok,true);assert.equal(r.authority,'LIVE_VERIFY');assert.equal(writes,1)})
 await check('planner rejects sources requiring sheet-name quoting before API access',async()=>{for(const sourceSheet of ['EURO PIV 123',"O'Brien",'2026']){const r=await agent.executePivotTask({task:{operations:[createSpec({sourceSheet})]},api:{inspect(){throw new Error('must not open API')}}});assert.equal(r.outcome,'xlsx-pivot-source-sheet-quoting-unsupported');assert.equal(r.writeAllowed,false)}})
 console.log(failed?'XLSX PIVOT STATIC: FAIL':'XLSX PIVOT STATIC: PASS');process.exitCode=failed?1:0
})()
