'use strict'
const assert=require('assert')
const {executeAgentTaskInPersistentSession}=require('./xlsx-persistent-session.cjs')
function env(name,fallback){const v=process.env[name]||fallback;if(!v)throw new Error(`${name} is required`);return v}
async function resolvePassword(){if(process.env.EURO_NC_PASS)return process.env.EURO_NC_PASS;const {getSecret}=await import(process.env.MARVEEN_VAULT_MODULE||'/home/user/marveen/dist/web/vault.js');return getSecret(process.env.EURO_NC_PASS_VAULT_ID||'Elliot_nc_pass','xlsx-persistent-rename-live-acceptance')}
const suffix=String(Date.now()).slice(-7),source=`EURO Ren A ${suffix}`.slice(0,31),target=`EURO Ren B ${suffix}`.slice(0,31)
const task={operations:[{intent:'create_sheet',name:source},{intent:'write_range',sheet:source,range:'A1',values:[['rename-persist']]},{intent:'rename_sheet',sheet:source,name:target}]}
async function run(label,credentials){const r=await executeAgentTaskInPersistentSession({fileId:env('EURO_XLSX_FILE_ID','1231187'),task,credentials});console.log(`=== ${label} ===`);console.log(JSON.stringify(r,null,2));assert.equal(r.ok,true);assert.equal(r.authority,'LIVE_VERIFY');assert.equal(r.wholeTaskVerification?.ok,true);assert.equal(r.persistentSession?.oneEditorSession,true);return r}
;(async()=>{const credentials={url:env('EURO_NC_URL','https://mt-server.eu'),user:env('EURO_NC_USER','elliot'),pass:await resolvePassword()};console.log(`SOURCE=${source}`);console.log(`TARGET=${target}`);const first=await run('RENAME APPLIED TASK',credentials);assert.equal(first.noOp,false);assert.deepEqual(first.receipt.map(x=>x.status),['APPLIED','APPLIED','APPLIED']);assert.equal(first.persistentSession.writes,3);assert.equal(first.persistentSession.persistenceBarrier?.ok,true);const second=await run('RENAME IDEMPOTENCY TASK',credentials);assert.equal(second.ok,true);assert.equal(second.noOp,true);assert.ok(second.receipt.every(x=>x.status==='NO_OP_SATISFIED'));assert.equal(second.persistentSession.writes,0);assert.equal(second.persistentSession.persistenceBarrier,null);console.log('XLSX PERSISTENT RENAME LIVE ACCEPTANCE: PASS')})().catch(e=>{console.error(e&&e.stack||e);process.exitCode=1})
