'use strict'
const assert=require('assert')
const agent=require('./xlsx-agent-chart-task.cjs')
const persistent=require('./xlsx-persistent-chart.cjs')
const sheetInventory={ok:true,authority:'LIVE_READ',sheets:[{name:'Sheet1'}]}
function task(extra={}){return {operations:[{intent:'set_chart',sheet:'Sheet1',name:'Revenue Chart',range:'A1:B3',chartType:'bar',title:'Revenue',width:3600000,height:2160000,expectedSeriesCount:1,...extra}]}}
function response(state,match,noOp=match){return {ok:true,source:'live-coedit-editor',noOp,state,applied:noOp?undefined:true,verification:{measurable:true,match}}}
async function run(name,fn){await fn();console.log('OK',name)}
;(async()=>{
 await run('planner canonicalizes exact measurable chart state',async()=>{const p=agent.planTask(task());assert.equal(p.ok,true);assert.equal(p.operation.title,'Revenue');assert.equal(p.operation.expectedSeriesCount,1)})
 await run('planner canonicalizes presentation, position and series state',async()=>{const p=agent.planTask(task({presentation:{legendPosition:'bottom',style:2,dataLabels:{showSeriesName:false,showCategoryName:false,showValue:true,showPercent:false}},chartPosition:{fromCol:4,colOffset:0,fromRow:1,rowOffset:0},series:[{index:0,name:'Sales',valuesRange:'=Sheet1!$B$2:$B$3',categoryRange:'Sheet1!$A$2:$A$3'}]}));assert.equal(p.ok,true);assert.equal(p.operation.series[0].valuesRange,'Sheet1!$B$2:$B$3');assert.equal(p.operation.chartPosition.fromCol,4)})
 await run('planner rejects incomplete data-label state and duplicate series indexes',async()=>{assert.equal(agent.planTask(task({presentation:{dataLabels:{showValue:true}}})).ok,false);assert.equal(agent.planTask(task({series:[{index:0,name:'A'},{index:0,name:'B'}]})).ok,false)})
 await run('planner rejects missing semantic series count',async()=>{assert.equal(agent.planTask(task({expectedSeriesCount:undefined})).ok,false)})
 await run('planner requires a full rename fingerprint',async()=>{assert.equal(agent.planTask({operations:[{intent:'rename_chart',sheet:'Sheet1',name:'Old',newName:'New',chartType:'bar',title:'Revenue',expectedSeriesCount:1}]}).ok,false);const p=agent.planTask({operations:[{intent:'rename_chart',sheet:'Sheet1',name:'Old',newName:'New',chartType:'bar',title:'Revenue',width:3600000,height:2160000,expectedSeriesCount:1}]});assert.equal(p.ok,true);assert.equal(p.operation.newName,'New')})
 await run('state matcher rejects duplicate names',async()=>{const s=persistent.stateOf({charts:[{name:'C'},{name:'C'}]},{name:'C'});assert.equal(s.count,2);assert.equal(persistent.match(s,{intent:'delete_chart'}),false)})
 await run('semantic reader exposes public presentation, position and series getters',async()=>{const series={GetName:()=> '="Sales"',GetValues:()=> '=Sheet1!$B$2:$B$3',GetCatFormula:()=> 'Sheet1!$A$2:$A$3'};const chart={GetName:()=> 'C',GetChartType:()=> 'bar',GetTitle:()=> 'Revenue\n',GetWidth:()=> 10,GetHeight:()=> 20,GetAllSeries:()=>[series],GetLegendPos:()=> 'bottom',GetHorAxisTitle:()=> 'Month\n',GetVerAxisTitle:()=> 'Revenue\n',GetDataLabels:()=>({showSerName:false,showCatName:false,showVal:true,showPercent:false}),GetChartStyle:()=>2,GetPosition:()=>({fromCol:4,colOffset:0,fromRow:1,rowOffset:0})};global.Api={GetSheet:()=>({GetAllCharts:()=>[chart]})};const r=persistent.chartSemanticStateCommand({intent:'set_chart',sheet:'Sheet1',name:'C',presentation:{legendPosition:'bottom',horizontalAxisTitle:'Month',verticalAxisTitle:'Revenue',dataLabels:{},style:2},chartPosition:{},series:[{index:0,name:'Sales',valuesRange:'Sheet1!$B$2:$B$3',categoryRange:'Sheet1!$A$2:$A$3'}]});assert.equal(r.ok,true);assert.equal(r.state.title,'Revenue');assert.equal(r.state.series[0].name,'Sales');assert.equal(r.state.series[0].valuesRange,'Sheet1!$B$2:$B$3')})
 await run('semantic reader activates the exact chart sheet before persisted geometry getters',async()=>{let active='PivotSheet';const chart={GetName:()=> 'C',GetChartType:()=> 'bar',GetTitle:()=> 'Revenue',GetWidth:()=>active==='Sheet1'?10:0,GetHeight:()=>active==='Sheet1'?20:0,GetAllSeries:()=>[{}]},sheet={GetName:()=> 'Sheet1',SetActive:()=>{active='Sheet1'},GetAllCharts:()=>[chart]};global.Api={GetSheet:()=>sheet,GetActiveSheet:()=>sheet};const r=persistent.chartSemanticStateCommand({intent:'set_chart',sheet:'Sheet1',name:'C'});assert.equal(r.ok,true);assert.equal(r.state.width,10);assert.equal(r.state.height,20);assert.equal(active,'Sheet1')})
 await run('persisted zero geometry requires an exact durable identity',async()=>{const marker={GetName:()=> 'ChartSize_10x20',GetRefersTo:()=> '=Sheet1!$A$1:$B$3'},chart={GetName:()=> 'C',GetChartType:()=> 'bar',GetTitle:()=> 'Revenue',GetWidth:()=>0,GetHeight:()=>0,GetAllSeries:()=>[{}]},sheet={GetName:()=> 'Sheet1',SetActive:()=>{},GetAllCharts:()=>[chart]};global.Api={GetSheet:()=>sheet,GetActiveSheet:()=>sheet,GetDefName:()=>marker};const op={intent:'set_chart',sheet:'Sheet1',name:'C',chartType:'bar',title:'Revenue',width:10,height:20,expectedSeriesCount:1,geometryIdentityName:'ChartSize_10x20',geometryIdentityRef:'=Sheet1!$A$1:$B$3'},r=persistent.chartSemanticStateCommand(op);assert.equal(r.ok,true);assert.equal(r.state.geometryReadback,'durable-identity-fallback');assert.equal(persistent.match(r.state,op),true);global.Api.GetDefName=()=>({...marker,GetRefersTo:()=> '=Sheet1!$A$1:$B$4'});const bad=persistent.chartSemanticStateCommand(op);assert.equal(persistent.match(bad.state,op),false)})
 await run('planner binds geometry identity to canonical size and a valid range',async()=>{const p=agent.planTask(task({geometryIdentityName:'ChartSize'}));assert.equal(p.ok,true);assert.equal(p.operation.geometryIdentityName,'ChartSize_3600000x2160000');assert.equal(p.operation.geometryIdentityRef,'=Sheet1!$A$1:$B$3')})
 await run('advanced mutation ordering reapplies presentation after style and data',async()=>{const op=agent.planTask(task({presentation:{legendPosition:'bottom',horizontalAxisTitle:'Month',verticalAxisTitle:'Revenue',dataLabels:{showSeriesName:false,showCategoryName:false,showValue:true,showPercent:false},style:2},chartPosition:{fromCol:4,colOffset:0,fromRow:1,rowOffset:0},series:[{index:0,name:'Sales'}]})).operation;const types=persistent.advancedMutationSpecs({},op).map(x=>x.spec.type);assert.deepEqual(types,['chart.presentation.style','chart.data.seriesName','chart.object.position','chart.presentation.legend','chart.presentation.axisTitles','chart.presentation.dataLabels'])})
 await run('rename retry requires source absence and exact target fingerprint',async()=>{const op=agent.planTask({operations:[{intent:'rename_chart',sheet:'Sheet1',name:'Old',newName:'New',chartType:'bar',title:'Revenue',width:3600000,height:2160000,expectedSeriesCount:1}]}).operation,absent=n=>({measurable:true,present:false,count:0,name:n}),present={measurable:true,present:true,count:1,name:'New',chartType:'bar',title:'Revenue',width:3600000,height:2160000,seriesCount:1};assert.equal(persistent.match({measurable:true,source:absent('Old'),target:present},op),true);assert.equal(persistent.match({measurable:true,source:{...present,name:'Old'},target:present},op),false)})
 await run('executor applies then whole-verifies',async()=>{let n=0;const absent={measurable:true,present:false,count:0,name:'Revenue Chart'},present={measurable:true,present:true,count:1,name:'Revenue Chart',chartType:'bar',title:'Revenue',width:3600000,height:2160000,seriesCount:1};const r=await agent.executeChartTask({task:task(),api:{inspect:async()=>sheetInventory,chartObserved:async(_op,apply)=>{n++;return apply?response(present,true,false):n<3?response(absent,false,false):response(present,true,true)}}});assert.equal(r.ok,true);assert.equal(r.noOp,false)})
 await run('executor recognizes exact no-op',async()=>{const present={measurable:true,present:true,count:1,name:'Revenue Chart',chartType:'bar',title:'Revenue',width:3600000,height:2160000,seriesCount:1};const r=await agent.executeChartTask({task:task(),api:{inspect:async()=>sheetInventory,chartObserved:async()=>response(present,true,true)}});assert.equal(r.ok,true);assert.equal(r.noOp,true)})
 await run('executor applies rename and verifies target-only final identity',async()=>{const t={operations:[{intent:'rename_chart',sheet:'Sheet1',name:'Old',newName:'New',chartType:'bar',title:'Revenue',width:3600000,height:2160000,expectedSeriesCount:1}]},absent=n=>({measurable:true,present:false,count:0,name:n}),old={measurable:true,present:true,count:1,name:'Old',chartType:'bar',title:'Revenue',width:3600000,height:2160000,seriesCount:1},renamed={...old,name:'New'},before={measurable:true,source:old,target:absent('New')},after={measurable:true,source:absent('Old'),target:renamed};let n=0;const r=await agent.executeChartTask({task:t,api:{inspect:async()=>sheetInventory,chartObserved:async(_op,apply)=>{n++;return apply?response(after,true,false):n<3?response(before,false,false):response(after,true,true)}}});assert.equal(r.ok,true);assert.equal(r.noOp,false);assert.equal(r.receipt[0].resolvedTarget.name,'New')})
 await run('executor fails closed on changed mutation boundary',async()=>{let n=0;const a={measurable:true,present:false,count:0,name:'Revenue Chart'},b={...a,count:2,present:true};const r=await agent.executeChartTask({task:task(),api:{inspect:async()=>sheetInventory,chartObserved:async()=>response(++n===1?a:b,false,false)}});assert.equal(r.ok,false);assert.equal(r.outcome,'xlsx-chart-task-state-changed-before-mutation')})
 console.log('XLSX CHART STATIC: PASS')
})().catch(e=>{console.error(e?.stack||e);process.exitCode=1})
