'use strict'
const assert=require('assert')
const fs=require('fs')
const wrapper=fs.readFileSync(require.resolve('./xlsx-persistent-copy-chain.cjs'),'utf8')
const canonical=fs.readFileSync(require.resolve('./xlsx-persistent-session.cjs'),'utf8')
assert.match(wrapper,/executeAgentTaskInPersistentSession/)
assert.doesNotMatch(wrapper,/classifyCopyChainRetry/)
assert.doesNotMatch(wrapper,/withPersistentXlsxSession/)
assert.match(canonical,/copyChainRetry\.classifyCopyChainRetry/)
assert.match(canonical,/if\(retry\.matched\)return/)
console.log('XLSX PERSISTENT COPY CHAIN RETRY WRAPPER STATIC: PASS')
