'use strict'
const assert=require('assert/strict'),batch=require('./xlsx-persistent-batch.cjs')
const FILE_ID=String(process.env.EURO_XLSX_PERSISTENT_FILE_ID||1231187)
process.env.EURO_PLAYWRIGHT_PATH=process.env.EURO_PLAYWRIGHT_PATH||'/home/user/marveen/node_modules/playwright'
function secret(id){const v=require('/home/user/marveen/dist/web/vault.js');const r=v.getSecret(id,'xlsx-structural-batch-live');if(!r)throw new Error('vault secret not found: '+id);return r}
const options={url:process.env.EURO_NEXTCLOUD_URL||'https://mt-server.eu',user:process.env.EURO_NEXTCLOUD_USER||'elliot',pass:secret('Elliot_nc_pass'),fileId:FILE_ID,timeoutMs:30000,pollMs:50}
function view(r){return {ok:r.ok,outcome:r.outcome,authority:r.authority,noOp:r.noOp,writes:r.persistentSession?.writes,barrier:r.persistentSession?.persistenceBarrier,checks:r.wholeTaskVerification?.checks,steps:r.steps?.map(s=>({index:s.index,intent:s.intent,outcome:s.result?.outcome,noOp:s.result?.noOp,hasRetryToken:!!s.result?.retryToken})),failed:r.failed,wholeTaskVerification:r.wholeTaskVerification}}
;(async()=>{const tag=String(Date.now()).slice(-7),sheet='EURO SB '+tag,base={operations:[{intent:'create_sheet',name:sheet},{intent:'write_range',sheet,range:'A1:C4',values:[[10,1,null],[20,2,null],[30,3,null],[40,4,null]],formulas:[[null,null,'=A1+B1'],[null,null,'=A2+B2'],[null,null,'=A3+B3'],[null,null,'=A4+B4']]},{intent:'insert_rows',sheet,range:'A2'}]}
const first=await batch.executeBatchTaskInPersistentSession({...options,task:base});console.log('STRUCTURAL BATCH FIRST',JSON.stringify(view(first),null,2));if(!first.ok){const dbg=await require('./xlsx-persistent-session.cjs').withPersistentXlsxSession(options,async(_s,api)=>({top:await api.readRange(sheet,'A1:C1'),inserted:await api.readRange(sheet,'A2:C2'),bottom:await api.readRange(sheet,'A3:C5')}));console.log('STRUCTURAL BATCH FAILURE LIVE STATE',JSON.stringify(dbg,null,2))};assert.equal(first.ok,true);assert.equal(first.authority,'LIVE_VERIFY');assert.equal(first.noOp,false);assert.equal(first.persistentSession?.oneEditorSession,true);assert.equal(first.persistentSession?.persistenceBarrier?.ok,true);assert.equal(first.wholeTaskVerification?.checks?.every(x=>x.ok),true)
const applied=first.steps.find(s=>s.intent==='insert_rows')?.result;assert.ok(applied?.retryToken);const retryTask={operations:base.operations.map(op=>op.intent==='insert_rows'?{...op,retryToken:applied.retryToken}:op)}
const retry=await batch.executeBatchTaskInPersistentSession({...options,task:retryTask});console.log('STRUCTURAL BATCH RETRY',JSON.stringify(view(retry),null,2));assert.equal(retry.ok,true);assert.equal(retry.authority,'LIVE_VERIFY');assert.equal(retry.noOp,true);assert.equal(retry.persistentSession?.writes,0);assert.equal(retry.persistentSession?.persistenceBarrier,null);assert.equal(retry.wholeTaskVerification?.checks?.every(x=>x.ok),true)
console.log('XLSX STRUCTURAL BATCH LIVE ACCEPTANCE: PASS')})().catch(e=>{console.error(e?.stack||e);process.exitCode=1})
