'use strict'
const assert=require('assert')
const {planTask,executeTask}=require('./xlsx-agent-task.cjs')
const {shouldPersistVerifiedTask}=require('./xlsx-persistent-session.cjs')
function inv(names){return {ok:true,authority:'LIVE_READ',sheets:names.map((name,index)=>({name,index}))}}
function read(sheet,range,value){return {ok:true,authority:'LIVE_READ',sheet,range,rows:1,columns:1,cells:[[{address:range,rawValue:value,value,displayText:String(value),formula:null,dataType:typeof value==='number'?'number':'string'}]]}}
async function dependencyChain(){let sheets=['Base'],cells={};let inspectCount=0,createCount=0,writeCount=0;const api={inspect:async()=>{inspectCount++;return inv(sheets)},readRange:async({sheet,range})=>read(sheet,range,cells[`${sheet}!${range}`]??''),createSheetVerified:async name=>{createCount++;sheets=[...sheets,name];return {ok:true,authority:'LIVE_VERIFY'}},writeRangeVerified:async spec=>{writeCount++;cells[`${spec.sheet}!${spec.range}`]=spec.values[0][0];return {ok:true,authority:'LIVE_VERIFY'}}};const task={operations:[{intent:'create_sheet',name:'AgentChain'},{intent:'write_range',sheet:'AgentChain',range:'A1',values:[[42]]}]};const r=await executeTask({task,api});assert.equal(r.ok,true);assert.equal(r.authority,'LIVE_VERIFY');assert.equal(r.wholeTaskVerification.ok,true);assert.equal(createCount,1);assert.equal(writeCount,1);assert.ok(inspectCount>=4);assert.equal(r.receipt[1].resolvedTarget.sheet,'AgentChain')}
async function renameDependency(){let sheets=['Base'],cells={};const api={inspect:async()=>inv(sheets),readRange:async({sheet,range})=>read(sheet,range,cells[`${sheet}!${range}`]??''),createSheetVerified:async name=>{sheets.push(name);return {ok:true,authority:'LIVE_VERIFY'}},writeRangeVerified:async spec=>{cells[`${spec.sheet}!${spec.range}`]=spec.values[0][0];return {ok:true,authority:'LIVE_VERIFY'}},renameSheetVerified:async(from,to)=>{sheets=sheets.map(x=>x===from?to:x);cells[`${to}!A1`]=cells[`${from}!A1`];delete cells[`${from}!A1`];return {ok:true,authority:'LIVE_VERIFY'}}};const task={operations:[{intent:'create_sheet',name:'Before'},{intent:'write_range',sheet:'Before',range:'A1',values:[[7]]},{intent:'rename_sheet',sheet:'Before',name:'After'}]};const first=await executeTask({task,api});assert.equal(first.ok,true);assert.equal(first.authority,'LIVE_VERIFY');assert.deepEqual(first.receipt.map(x=>x.status),['APPLIED','APPLIED','APPLIED']);assert.equal(first.wholeTaskVerification.checks[0].sheet,'After');assert.equal(first.wholeTaskVerification.checks[1].sheet,'After');const second=await executeTask({task,api});assert.equal(second.ok,true);assert.equal(second.noOp,true);assert.ok(second.receipt.every(x=>x.status==='NO_OP_SATISFIED'));assert.equal(second.receipt[0].resolvedTarget.sheet,'After');assert.equal(second.receipt[1].resolvedTarget.sheet,'After')}
async function deleteSheet(){let sheets=['Keep','Drop'],deletes=0;const api={inspect:async()=>inv(sheets),deleteSheetVerified:async name=>{deletes++;sheets=sheets.filter(x=>x!==name);return {ok:true,authority:'LIVE_VERIFY'}}};const task={operations:[{intent:'delete_sheet',sheet:'Drop'}]};const first=await executeTask({task,api});assert.equal(first.ok,true);assert.equal(first.authority,'LIVE_VERIFY');assert.equal(first.noOp,false);assert.equal(first.receipt[0].status,'APPLIED');assert.equal(first.wholeTaskVerification.checks[0].status,'PASS');assert.equal(deletes,1);const second=await executeTask({task,api});assert.equal(second.ok,true);assert.equal(second.noOp,true);assert.equal(second.receipt[0].status,'NO_OP_SATISFIED');assert.equal(deletes,1)}
async function deleteLastSheet(){let deletes=0;const api={inspect:async()=>inv(['Only']),deleteSheetVerified:async()=>{deletes++;throw new Error('must not delete last sheet')}};const r=await executeTask({task:{operations:[{intent:'delete_sheet',sheet:'Only'}]},api});assert.equal(r.ok,false);assert.equal(r.outcome,'xlsx-delete-last-sheet-refused');assert.equal(r.authority,'PLAN_ONLY');assert.equal(deletes,0)}
function deleteDependencyGates(){const afterWrite=planTask({operations:[{intent:'write_range',sheet:'S',range:'A1',values:[[1]]},{intent:'delete_sheet',sheet:'S'}]});assert.equal(afterWrite.ok,false);assert.equal(afterWrite.outcome,'xlsx-task-delete-after-dependent-mutation-not-supported');assert.equal(afterWrite.authority,'PLAN_ONLY');const afterCreate=planTask({operations:[{intent:'create_sheet',name:'S'},{intent:'delete_sheet',sheet:'S'}]});assert.equal(afterCreate.ok,false);assert.equal(afterCreate.outcome,'xlsx-task-delete-after-dependent-mutation-not-supported');const referenceAfter=planTask({operations:[{intent:'delete_sheet',sheet:'S'},{intent:'write_range',sheet:'S',range:'A1',values:[[1]]}]});assert.equal(referenceAfter.ok,false);assert.equal(referenceAfter.outcome,'xlsx-task-reference-after-delete-not-supported');const renameAfter=planTask({operations:[{intent:'delete_sheet',sheet:'S'},{intent:'rename_sheet',sheet:'S',name:'T'}]});assert.equal(renameAfter.ok,false);assert.equal(renameAfter.outcome,'xlsx-task-reference-after-delete-not-supported');const independent=planTask({operations:[{intent:'delete_sheet',sheet:'S'},{intent:'write_range',sheet:'Other',range:'A1',values:[[1]]}]});assert.equal(independent.ok,true)}
async function noop(){let writes=0,creates=0;const api={inspect:async()=>inv(['AgentChain']),readRange:async()=>read('AgentChain','A1',42),createSheetVerified:async()=>{creates++;throw new Error('must not create')},writeRangeVerified:async()=>{writes++;throw new Error('must not write')}};const r=await executeTask({task:{operations:[{intent:'create_sheet',name:'AgentChain'},{intent:'write_range',sheet:'AgentChain',range:'A1',values:[[42]]}]},api});assert.equal(r.ok,true);assert.equal(r.noOp,true);assert.equal(creates,0);assert.equal(writes,0);assert.ok(r.receipt.every(x=>x.status==='NO_OP_SATISFIED'))}
async function missingTarget(){let writes=0;const api={inspect:async()=>inv(['Base']),readRange:async()=>{throw new Error('must not read missing sheet')},writeRangeVerified:async()=>{writes++;throw new Error('must not write')}};const r=await executeTask({task:{operations:[{intent:'write_range',sheet:'Missing',range:'A1',values:[[1]]}]},api});assert.equal(r.ok,false);assert.equal(r.outcome,'xlsx-target-sheet-not-found');assert.equal(r.authority,'PLAN_ONLY');assert.equal(writes,0)}
async function unsupported(){const p=planTask({operations:[{intent:'chart_magic'}]});assert.equal(p.ok,false);assert.equal(p.outcome,'xlsx-task-intent-not-supported');assert.equal(p.authority,'PLAN_ONLY');assert.equal(p.writeAllowed,false)}
function invalidWrites(){const cases=[{sheet:'S',range:'A1:B2',values:[[1,2]]},{sheet:'S',range:'A1:B2',values:[[1,2],[3]]},{sheet:'S',range:'A1',values:[[1]],formulas:[['B1*2']]},{sheet:'S',range:'A1:B1',values:[[1,2]],formulas:[[null]]},{sheet:'',range:'A1',values:[[1]]}];for(const op of cases){const p=planTask({operations:[{intent:'write_range',...op}]});assert.equal(p.ok,false);assert.equal(p.authority,'PLAN_ONLY');assert.equal(p.writeAllowed,false)}}
function overlapGate(){const conflict=planTask({operations:[{intent:'write_range',sheet:'S',range:'A1:B2',values:[[1,2],[3,4]]},{intent:'write_range',sheet:'S',range:'B2:C3',values:[[5,6],[7,8]]}]});assert.equal(conflict.ok,false);assert.equal(conflict.outcome,'xlsx-task-overlapping-writes-not-supported');assert.equal(conflict.authority,'PLAN_ONLY');assert.equal(conflict.writeAllowed,false);assert.deepEqual(conflict.conflict,{sheet:'S',first:{index:0,range:'A1:B2'},second:{index:1,range:'B2:C3'}});const adjacent=planTask({operations:[{intent:'write_range',sheet:'S',range:'A1:A2',values:[[1],[2]]},{intent:'write_range',sheet:'S',range:'B1:B2',values:[[3],[4]]}]});assert.equal(adjacent.ok,true);const otherSheet=planTask({operations:[{intent:'write_range',sheet:'S1',range:'A1',values:[[1]]},{intent:'write_range',sheet:'S2',range:'A1',values:[[2]]}]});assert.equal(otherSheet.ok,true)}
async function finalRegression(){let phase='before';const api={inspect:async()=>inv(['S']),readRange:async()=>read('S','A1',phase==='before'?0:99),writeRangeVerified:async()=>{phase='after';return {ok:true,authority:'LIVE_VERIFY'}}};const r=await executeTask({task:{operations:[{intent:'write_range',sheet:'S',range:'A1',values:[[7]]}]},api});assert.equal(r.ok,false);assert.equal(r.outcome,'xlsx-task-whole-verify-failed');assert.notEqual(r.authority,'LIVE_VERIFY')}
function persistenceAuthority(){assert.equal(shouldPersistVerifiedTask({ok:true,authority:'LIVE_VERIFY',noOp:false},{writes:2}),true);assert.equal(shouldPersistVerifiedTask({ok:true,authority:'LIVE_VERIFY',noOp:true},{writes:0}),false);assert.equal(shouldPersistVerifiedTask({ok:false,authority:'PRIMITIVE_LIVE_VERIFY_ONLY',noOp:false},{writes:1}),false);assert.equal(shouldPersistVerifiedTask({ok:false,authority:'LIVE_READ',noOp:false},{writes:1}),false);assert.equal(shouldPersistVerifiedTask({ok:true,authority:'LIVE_VERIFY',noOp:false},{writes:0}),false)}
;(async()=>{await dependencyChain();await renameDependency();await deleteSheet();await deleteLastSheet();deleteDependencyGates();await noop();await missingTarget();await unsupported();invalidWrites();overlapGate();await finalRegression();persistenceAuthority();console.log('XLSX PERSISTENT TASK STATIC: PASS')})().catch(e=>{console.error(e);process.exitCode=1})
