'use strict'
const assert=require('assert')
const {planCopyTask,executeCopyTask}=require('./xlsx-agent-copy-task.cjs')
function inv(names,used='A1:B1'){return {ok:true,authority:'LIVE_READ',sheets:names.map((name,index)=>({name,index,usedRange:used}))}}
function rr(values){return {ok:true,authority:'LIVE_READ',rows:1,columns:2,cells:[values.map((v,i)=>({address:i?'B1':'A1',rawValue:v,value:v,displayText:String(v),formula:null,dataType:typeof v==='number'?'number':'string'}))]}}
async function applied(){let names=['Source'],copies=0;const api={inspect:async()=>inv(names),readRange:async({sheet})=>rr(sheet==='Source'?[1,2]:[1,2]),copySheetVerified:async()=>{copies++;names=['Source','Target'];return {ok:true,authority:'LIVE_VERIFY',noOp:false}}};const r=await executeCopyTask({task:{operations:[{intent:'copy_sheet',sheet:'Source',name:'Target'}]},api});assert.equal(r.ok,true);assert.equal(r.authority,'LIVE_VERIFY');assert.equal(r.noOp,false);assert.equal(r.receipt[0].status,'APPLIED');assert.equal(copies,1);assert.equal(r.wholeTaskVerification.checks[0].status,'PASS')}
async function noop(){let copies=0;const api={inspect:async()=>inv(['Source','Target']),readRange:async()=>rr([1,2]),copySheetVerified:async()=>{copies++;throw new Error('must not copy')}};const r=await executeCopyTask({task:{operations:[{intent:'copy_sheet',sheet:'Source',name:'Target'}]},api});assert.equal(r.ok,true);assert.equal(r.noOp,true);assert.equal(r.receipt[0].status,'NO_OP_SATISFIED');assert.equal(copies,0)}
async function mismatch(){let copies=0;const api={inspect:async()=>inv(['Source','Target']),readRange:async({sheet})=>rr(sheet==='Source'?[1,2]:[1,9]),copySheetVerified:async()=>{copies++}};const r=await executeCopyTask({task:{operations:[{intent:'copy_sheet',sheet:'Source',name:'Target'}]},api});assert.equal(r.ok,false);assert.equal(r.outcome,'xlsx-copy-task-existing-target-mismatch');assert.equal(r.authority,'PLAN_ONLY');assert.equal(copies,0)}
function planning(){assert.equal(planCopyTask({operations:[{intent:'copy_sheet',sheet:'A',name:'A'}]}).ok,false);assert.equal(planCopyTask({operations:[{intent:'copy_sheet',sheet:'A',name:'B'},{intent:'copy_sheet',sheet:'B',name:'C'}]}).ok,false);assert.equal(planCopyTask({operations:[{intent:'write_range',sheet:'A',range:'A1',values:[[1]]}]}).ok,false)}
;(async()=>{planning();await applied();await noop();await mismatch();console.log('XLSX AGENT COPY TASK STATIC: PASS')})().catch(e=>{console.error(e);process.exitCode=1})
