'use strict'
const assert=require('assert')
const {planTask,executeTask}=require('./xlsx-agent-task.cjs')
const {shouldPersistVerifiedTask}=require('./xlsx-persistent-session.cjs')
function inv(names){return {ok:true,authority:'LIVE_READ',sheets:names.map((name,index)=>({name,index}))}}
function read(sheet,range,value){return {ok:true,authority:'LIVE_READ',sheet,range,rows:1,columns:1,cells:[[{address:range,rawValue:value,value,displayText:String(value),formula:null,dataType:typeof value==='number'?'number':'string'}]]}}
async function dependencyChain(){let sheets=['Base'],cells={};let inspectCount=0,createCount=0,writeCount=0;const api={inspect:async()=>{inspectCount++;return inv(sheets)},readRange:async({sheet,range})=>read(sheet,range,cells[`${sheet}!${range}`]??''),createSheetVerified:async name=>{createCount++;sheets=[...sheets,name];return {ok:true,authority:'LIVE_VERIFY'}},writeRangeVerified:async spec=>{writeCount++;cells[`${spec.sheet}!${spec.range}`]=spec.values[0][0];return {ok:true,authority:'LIVE_VERIFY'}}};const task={operations:[{intent:'create_sheet',name:'AgentChain'},{intent:'write_range',sheet:'AgentChain',range:'A1',values:[[42]]}]};const r=await executeTask({task,api});assert.equal(r.ok,true);assert.equal(r.authority,'LIVE_VERIFY');assert.equal(r.wholeTaskVerification.ok,true);assert.equal(createCount,1);assert.equal(writeCount,1);assert.ok(inspectCount>=4);assert.equal(r.receipt[1].resolvedTarget.sheet,'AgentChain')}
async function noop(){let writes=0,creates=0;const api={inspect:async()=>inv(['AgentChain']),readRange:async()=>read('AgentChain','A1',42),createSheetVerified:async()=>{creates++;throw new Error('must not create')},writeRangeVerified:async()=>{writes++;throw new Error('must not write')}};const r=await executeTask({task:{operations:[{intent:'create_sheet',name:'AgentChain'},{intent:'write_range',sheet:'AgentChain',range:'A1',values:[[42]]}]},api});assert.equal(r.ok,true);assert.equal(r.noOp,true);assert.equal(creates,0);assert.equal(writes,0);assert.ok(r.receipt.every(x=>x.status==='NO_OP_SATISFIED'))}
async function missingTarget(){let writes=0;const api={inspect:async()=>inv(['Base']),readRange:async()=>{throw new Error('must not read missing sheet')},writeRangeVerified:async()=>{writes++;throw new Error('must not write')}};const r=await executeTask({task:{operations:[{intent:'write_range',sheet:'Missing',range:'A1',values:[[1]]}]},api});assert.equal(r.ok,false);assert.equal(r.outcome,'xlsx-target-sheet-not-found');assert.equal(r.authority,'PLAN_ONLY');assert.equal(writes,0)}
async function unsupported(){const p=planTask({operations:[{intent:'chart_magic'}]});assert.equal(p.ok,false);assert.equal(p.outcome,'xlsx-task-intent-not-supported');assert.equal(p.authority,'PLAN_ONLY');assert.equal(p.writeAllowed,false)}
function invalidWrites(){const cases=[{sheet:'S',range:'A1:B2',values:[[1,2]]},{sheet:'S',range:'A1:B2',values:[[1,2],[3]]},{sheet:'S',range:'A1',values:[[1]],formulas:[['B1*2']]},{sheet:'S',range:'A1:B1',values:[[1,2]],formulas:[[null]]},{sheet:'',range:'A1',values:[[1]]}];for(const op of cases){const p=planTask({operations:[{intent:'write_range',...op}]});assert.equal(p.ok,false);assert.equal(p.authority,'PLAN_ONLY');assert.equal(p.writeAllowed,false)}}
async function finalRegression(){let phase='before';const api={inspect:async()=>inv(['S']),readRange:async()=>read('S','A1',phase==='before'?0:99),writeRangeVerified:async()=>{phase='after';return {ok:true,authority:'LIVE_VERIFY'}}};const r=await executeTask({task:{operations:[{intent:'write_range',sheet:'S',range:'A1',values:[[7]]}]},api});assert.equal(r.ok,false);assert.equal(r.outcome,'xlsx-task-whole-verify-failed');assert.notEqual(r.authority,'LIVE_VERIFY')}
function persistenceAuthority(){assert.equal(shouldPersistVerifiedTask({ok:true,authority:'LIVE_VERIFY',noOp:false},{writes:2}),true);assert.equal(shouldPersistVerifiedTask({ok:true,authority:'LIVE_VERIFY',noOp:true},{writes:0}),false);assert.equal(shouldPersistVerifiedTask({ok:false,authority:'PRIMITIVE_LIVE_VERIFY_ONLY',noOp:false},{writes:1}),false);assert.equal(shouldPersistVerifiedTask({ok:false,authority:'LIVE_READ',noOp:false},{writes:1}),false);assert.equal(shouldPersistVerifiedTask({ok:true,authority:'LIVE_VERIFY',noOp:false},{writes:0}),false)}
;(async()=>{await dependencyChain();await noop();await missingTarget();await unsupported();invalidWrites();await finalRegression();persistenceAuthority();console.log('XLSX PERSISTENT TASK STATIC: PASS')})().catch(e=>{console.error(e);process.exitCode=1})
