'use strict'
const assert=require('assert/strict'),batch=require('./xlsx-persistent-batch.cjs')
const FILE_ID=String(process.env.EURO_XLSX_PERSISTENT_FILE_ID||1231187)
process.env.EURO_PLAYWRIGHT_PATH=process.env.EURO_PLAYWRIGHT_PATH||'/home/user/marveen/node_modules/playwright'
function secret(id){const v=require('/home/user/marveen/dist/web/vault.js');const r=v.getSecret(id,'xlsx-autofit-batch-live');if(!r)throw new Error('vault secret not found: '+id);return r}
const options={url:process.env.EURO_NEXTCLOUD_URL||'https://mt-server.eu',user:process.env.EURO_NEXTCLOUD_USER||'elliot',pass:secret('Elliot_nc_pass'),fileId:FILE_ID,timeoutMs:30000,pollMs:50}
function view(r){return {ok:r.ok,outcome:r.outcome,authority:r.authority,noOp:r.noOp,writes:r.persistentSession?.writes,barrier:r.persistentSession?.persistenceBarrier,checks:r.wholeTaskVerification?.checks,steps:r.steps?.map(s=>({index:s.index,intent:s.intent,outcome:s.result?.outcome,noOp:s.result?.noOp,hasRetryToken:!!s.result?.retryToken}))}}
;(async()=>{const tag=String(Date.now()).slice(-7),sheet='EURO AFB '+tag
const seed=await batch.executeBatchTaskInPersistentSession({...options,task:{operations:[{intent:'create_sheet',name:sheet},{intent:'write_range',sheet,range:'A1:C3',values:[['A very long heading that should force a wider column','x','y'],['another long value for autofit verification','short','short'],['third long value','z','z']]},{intent:'layout_range',sheet,range:'A1:A3',type:'column.width',width:5}]}});assert.equal(seed.ok,true)
const task={operations:[{intent:'layout_range',sheet,range:'A1:A3',type:'columns.autofit'}]}
const first=await batch.executeBatchTaskInPersistentSession({...options,task});console.log('AUTOFIT BATCH FIRST',JSON.stringify(view(first),null,2));assert.equal(first.ok,true);assert.equal(first.authority,'LIVE_VERIFY');assert.equal(first.noOp,false);assert.equal(first.persistentSession?.writes,1);assert.equal(first.persistentSession?.persistenceBarrier?.ok,true);const applied=first.steps.find(s=>s.intent==='layout_range')?.result;assert.ok(applied?.retryToken)
const retry=await batch.executeBatchTaskInPersistentSession({...options,task:{operations:[{...task.operations[0],retryToken:applied.retryToken}]}});console.log('AUTOFIT BATCH RETRY',JSON.stringify(view(retry),null,2));assert.equal(retry.ok,true);assert.equal(retry.authority,'LIVE_VERIFY');assert.equal(retry.noOp,true);assert.equal(retry.persistentSession?.writes,0);assert.equal(retry.persistentSession?.persistenceBarrier,null)
console.log('XLSX AUTOFIT BATCH LIVE ACCEPTANCE: PASS')})().catch(e=>{console.error(e?.stack||e);process.exitCode=1})
