'use strict'
const assert=require('assert')
const {dataValidationCommand}=require('./live-data-validation.cjs')
let failed=0
function check(n,fn){try{fn();console.log('OK    '+n)}catch(e){failed++;console.log('FAIL  '+n+'\n      '+(e.stack||e))}}
function fixture(){const s={type:'xlValidateInputOnly',alertStyle:null,operator:null,formula1:'',formula2:'',ignoreBlank:true,inCellDropdown:true,inputMessage:'',inputTitle:'',showError:true,showInput:true,errorMessage:'',errorTitle:''};const v={Add(t,a,o,f1,f2){Object.assign(s,{type:t,alertStyle:a,operator:o,formula1:String(f1),formula2:f2==null?'':String(f2)})},Modify(t,a,o,f1,f2){this.Add(t,a,o,f1,f2)},Delete(){Object.assign(s,{type:'xlValidateInputOnly',alertStyle:null,operator:null,formula1:'',formula2:''})}};for(const k of ['Type','AlertStyle','Operator','Formula1','Formula2','IgnoreBlank','InCellDropdown','InputMessage','InputTitle','ShowError','ShowInput','ErrorMessage','ErrorTitle'])v['Get'+k]=()=>s[k.charAt(0).toLowerCase()+k.slice(1)];for(const k of ['IgnoreBlank','InCellDropdown','InputMessage','InputTitle','ShowError','ShowInput','ErrorMessage','ErrorTitle'])v['Set'+k]=x=>{s[k.charAt(0).toLowerCase()+k.slice(1)]=x};const range={GetValidation(){return v}};return {s,api:{GetSheet(n){return n==='Sheet1'?{GetRange(){return range}}:null}}}}
function withApi(f,fn){const old=global.Api;global.Api=f.api;try{return fn()}finally{if(old===undefined)delete global.Api;else global.Api=old}}
check('add exact getter readback -> PASS',()=>{const f=fixture(),r=withApi(f,()=>dataValidationCommand({type:'validation.add',sheet:'Sheet1',range:'A1',validationType:'xlValidateWholeNumber',alertStyle:'xlValidAlertStop',operator:'xlBetween',formula1:'1',formula2:'10'}));assert.equal(r.verification.status,'PASS');assert.equal(r.verification.actual.type,'xlValidateWholeNumber')})
check('modify exact getter readback -> PASS',()=>{const f=fixture();withApi(f,()=>dataValidationCommand({type:'validation.add',sheet:'Sheet1',range:'A1',validationType:'xlValidateWholeNumber',formula1:'1',formula2:'10'}));const r=withApi(f,()=>dataValidationCommand({type:'validation.modify',sheet:'Sheet1',range:'A1',validationType:'xlValidateDecimal',operator:'xlGreater',formula1:'12'}));assert.equal(r.verification.status,'PASS');assert.equal(r.verification.actual.type,'xlValidateDecimal')})
check('options exact getter readback -> PASS',()=>{const f=fixture(),r=withApi(f,()=>dataValidationCommand({type:'validation.options',sheet:'Sheet1',range:'A1',ignoreBlank:false,inputTitle:'M6.2',inputMessage:'Enter value',showInput:true,errorTitle:'Invalid',errorMessage:'Try again',showError:true}));assert.equal(r.verification.status,'PASS');assert.equal(r.verification.actual.inputTitle,'M6.2')})
check('inspect -> PASS',()=>{const f=fixture(),r=withApi(f,()=>dataValidationCommand({type:'validation.inspect',sheet:'Sheet1',range:'A1'}));assert.equal(r.verification.status,'PASS')})
check('delete verifies input-only/absent state -> PASS',()=>{const f=fixture(),r=withApi(f,()=>dataValidationCommand({type:'validation.delete',sheet:'Sheet1',range:'A1'}));assert.equal(r.verification.status,'PASS')})
check('unknown operation fails closed',()=>{const f=fixture(),r=withApi(f,()=>dataValidationCommand({type:'wat',sheet:'Sheet1',range:'A1'}));assert.equal(r.outcome,'invalid-operation')})
console.log('\n'+(failed===0?'MIND OK':failed+' FAILED'));process.exit(failed?1:0)
