'use strict'
const assert=require('assert')
const {executeAgentTaskInPersistentSession,executeCopyTaskInPersistentSession,withPersistentXlsxSession}=require('./xlsx-persistent-session.cjs')
const FILE_ID=Number(process.env.EURO_XLSX_PERSISTENT_FILE_ID||1231187)
process.env.EURO_PLAYWRIGHT_PATH=process.env.EURO_PLAYWRIGHT_PATH||'/home/user/marveen/node_modules/playwright'
function secret(id){const v=require('/home/user/marveen/dist/web/vault.js');const r=v.getSecret(id,'xlsx-persistent-copy-live-acceptance');if(!r)throw new Error(`vault secret not found: ${id}`);return r}
const credentials={url:process.env.EURO_NEXTCLOUD_URL||'https://mt-server.eu',user:process.env.EURO_NEXTCLOUD_USER||'elliot',pass:secret('Elliot_nc_pass')}
const sessionOptions={url:credentials.url,user:credentials.user,pass:credentials.pass,fileId:FILE_ID,timeoutMs:30000,pollMs:50}
async function setup(task){return executeAgentTaskInPersistentSession({fileId:FILE_ID,task,credentials,timeoutMs:30000,pollMs:50})}
async function copy(task){return executeCopyTaskInPersistentSession({fileId:FILE_ID,task,credentials,timeoutMs:30000,pollMs:50})}
async function probeNativeCopy(){return withPersistentXlsxSession(sessionOptions,async api=>{const s=api.session;const probe=await s.frame.evaluate((where)=>{const e=where==='window.editor'?window.editor:(window.Asc||{}).editor;return {ok:true,authority:'LIVE_READ',noOp:true,apiWhere:where,ascCopyWorksheet:typeof(e&&e.asc_copyWorksheet),ascGetActiveWorksheetIndex:typeof(e&&e.asc_getActiveWorksheetIndex),ascGetWorksheetName:typeof(e&&e.asc_getWorksheetName),ascGetWorksheetsCount:typeof(e&&e.asc_getWorksheetsCount)}},s.apiWhere);return probe})}
;(async()=>{const native=await probeNativeCopy();console.log('=== NATIVE COPY API PROBE ===');console.log(JSON.stringify(native,null,2));assert.equal(native.ok,true);assert.equal(native.authority,'LIVE_READ');assert.equal(native.ascCopyWorksheet,'function');const suffix=String(Date.now()).slice(-7),source=`EURO Copy A ${suffix}`,target=`EURO Copy B ${suffix}`;console.log(`SOURCE=${source}`);console.log(`TARGET=${target}`)
const fixture=await setup({operations:[{intent:'create_sheet',name:source},{intent:'write_range',sheet:source,range:'A1:B2',values:[[11,22],[33,44]],formulas:[[null,null],[null,'=A1+B1']]}]});console.log('=== COPY SETUP TASK ===');console.log(JSON.stringify(fixture,null,2));assert.equal(fixture.ok,true);assert.equal(fixture.authority,'LIVE_VERIFY');assert.equal(fixture.noOp,false);assert.ok(fixture.persistentSession?.persistenceBarrier?.ok)
const first=await copy({operations:[{intent:'copy_sheet',sheet:source,name:target}]});console.log('=== COPY APPLIED TASK ===');console.log(JSON.stringify(first,null,2));assert.equal(first.ok,true);assert.equal(first.authority,'LIVE_VERIFY');assert.equal(first.noOp,false);assert.equal(first.receipt?.[0]?.status,'APPLIED');assert.equal(first.wholeTaskVerification?.checks?.[0]?.status,'PASS');assert.equal(first.persistentSession?.writes,1);assert.ok(first.persistentSession?.persistenceBarrier?.ok)
const second=await copy({operations:[{intent:'copy_sheet',sheet:source,name:target}]});console.log('=== COPY IDEMPOTENCY TASK ===');console.log(JSON.stringify(second,null,2));assert.equal(second.ok,true);assert.equal(second.authority,'LIVE_VERIFY');assert.equal(second.noOp,true);assert.equal(second.receipt?.[0]?.status,'NO_OP_SATISFIED');assert.equal(second.wholeTaskVerification?.checks?.[0]?.status,'PASS');assert.equal(second.persistentSession?.writes,0);assert.equal(second.persistentSession?.persistenceBarrier,null)
console.log('XLSX PERSISTENT COPY LIVE ACCEPTANCE: PASS')})().catch(e=>{console.error(e);process.exitCode=1})