'use strict'
const assert=require('assert')
const {buildChartDeleteScript,parseChartDeleteMarker,verifyChartDelete}=require('./docbuilder-charts.cjs')
assert.throws(()=>buildChartDeleteScript({sheet:'Sheet1'}),/name required/)
assert.throws(()=>buildChartDeleteScript({name:'Chart 1'}),/sheet required/)
const s=buildChartDeleteScript({sheet:'Sheet1',name:'M51_test'})
assert.match(s,/builder\.OpenFile\("__DOC_URL__", "xlsx"\)/)
assert.match(s,/GetDrawingsByName\("M51_test"\)/)
assert.match(s,/\.Delete/)
assert.match(s,/builder\.SaveFile\("xlsx", "eredmeny\.xlsx"\)/)
const m=parseChartDeleteMarker('abc__EURO_M51_CHART_DELETE__:{"name":"M51_test","before":2,"after":1,"deleted":true}\nxyz')
assert.deepStrictEqual(m,{name:'M51_test',before:2,after:1,deleted:true})
assert.strictEqual(verifyChartDelete({name:'M51_test',marker:m}).status,'PASS')
assert.strictEqual(verifyChartDelete({name:'M51_test',marker:null}).status,'UNKNOWN')
assert.strictEqual(verifyChartDelete({name:'M51_test',marker:{name:'M51_test',before:2,after:2,deleted:true}}).status,'FAIL')
assert.strictEqual(verifyChartDelete({name:'M51_test',marker:{name:'M51_test',before:2,after:1,deleted:false}}).status,'FAIL')
console.log('test_docbuilder_charts.cjs: OK')
