'use strict'
const assert=require('assert'),v=require('./xlsx-structural-range-verifier.cjs')
const read=(cells,row=1,column=1)=>({ok:true,authority:'LIVE_READ',cells:cells.map((xs,r)=>xs.map((c,i)=>({...c,row:row+r,column:column+i,address:''})))}),x=n=>({value:n}),f=s=>({formula:s,value:0}),z=()=>({value:'',formula:null,dataType:'blank'})
let r=v.verifyRowsInsert(read([[x(1),f('=A2+B2')],[x(3),f('=A3+B3')]],2,1),read([[z(),z()],[x(1),f('=A3+B3')],[x(3),f('=A4+B4')]],2,1));assert.equal(r.ok,true)
r=v.verifyRowsDelete(read([[x(1),f('=A2+B2')],[x(3),f('=A3+B3')],[x(5),f('=A4+B4')]],2,1),read([[x(3),f('=A2+B2')],[x(5),f('=A3+B3')]],2,1));assert.equal(r.ok,true)
r=v.verifyColumnsInsert(read([[x(1),f('=A1+B1')],[x(3),f('=A2+B2')]],1,2),read([[z(),x(1),f('=A1+C1')],[z(),x(3),f('=A2+C2')]],1,2));assert.equal(r.ok,true)
r=v.verifyColumnsDelete(read([[x(1),x(2),x(3)],[x(4),x(5),x(6)]],1,2),read([[x(2),x(3)],[x(5),x(6)]],1,2));assert.equal(r.ok,true)
r=v.verifyRowsInsert(read([[x(1)]],2,1),read([[x(9)],[x(1)]],2,1));assert.equal(r.ok,false);assert.equal(r.outcome,'rows-insert-new-row-not-blank')
r=v.verifyColumnsDelete(read([[x(1),x(2)]],1,2),read([[x(1)]],1,2));assert.equal(r.ok,false);assert.equal(r.outcome,'columns-delete-shift-mismatch')
assert.equal(v.rewriteFormula('=A1+B1',{axis:'column',kind:'insert',boundary:2,count:1}),'=A1+C1')
assert.equal(v.rewriteFormula('=A1+B1',{axis:'column',kind:'delete',boundary:2,count:1}),'=A1+#REF!')
assert.equal(v.rewriteFormula('=A2+B2',{axis:'row',kind:'insert',boundary:2,count:1}),'=A3+B3')
console.log('XLSX STRUCTURAL RANGE VERIFIER STATIC: PASS')
