'use strict'
const assert=require('assert')
const {definedNameObserveCommand}=require('./xlsx-defined-name-observer.cjs')
const agent=require('./xlsx-agent-defined-name-task.cjs')
let failed=0
async function check(name,fn){try{await fn();console.log('OK '+name)}catch(e){failed++;console.error('FAIL '+name+'\n'+(e?.stack||e))}}
function fixture(){
 const names={},state={writes:0}
 function obj(name){const x=names[name];if(!x)throw new Error('missing');return {GetName:()=>x.name,GetRefersTo:()=>x.refersTo,SetName:v=>{state.writes++;delete names[x.name];x.name=v;names[v]=x},SetRefersTo:v=>{state.writes++;x.refersTo=v},Delete:()=>{state.writes++;delete names[x.name]}}}
 return {names,state,api:{GetDefName:obj,AddDefName:(n,r)=>{state.writes++;names[n]={name:n,refersTo:r}}}}
}
function withApi(f,fn){const old=global.Api;global.Api=f.api;try{return fn()}finally{if(old===undefined)delete global.Api;else global.Api=old}}
;(async()=>{
 await check('observer adds and exactly reads defined name',async()=>{const f=fixture(),r=withApi(f,()=>definedNameObserveCommand({intent:'set_defined_name',name:'EURO_NAME',refersTo:'=Sheet1!$A$1',apply:true}));assert.equal(r.ok,true);assert.equal(r.state.refersTo,'=Sheet1!$A$1');assert.equal(f.state.writes,1)})
 await check('observer recognizes exact set no-op',async()=>{const f=fixture();withApi(f,()=>definedNameObserveCommand({intent:'set_defined_name',name:'EURO_NAME',refersTo:'=Sheet1!$A$1',apply:true}));const r=withApi(f,()=>definedNameObserveCommand({intent:'set_defined_name',name:'EURO_NAME',refersTo:'=Sheet1!$A$1',apply:false}));assert.equal(r.noOp,true)})
 await check('observer updates reference',async()=>{const f=fixture();withApi(f,()=>definedNameObserveCommand({intent:'set_defined_name',name:'EURO_NAME',refersTo:'=Sheet1!$A$1',apply:true}));const r=withApi(f,()=>definedNameObserveCommand({intent:'set_defined_name',name:'EURO_NAME',refersTo:'=Sheet1!$B$2',apply:true}));assert.equal(r.ok,true);assert.equal(r.state.refersTo,'=Sheet1!$B$2');assert.equal(f.state.writes,2)})
 await check('observer renames with source and target proof',async()=>{const f=fixture();withApi(f,()=>definedNameObserveCommand({intent:'set_defined_name',name:'EURO_NAME',refersTo:'=Sheet1!$A$1',apply:true}));const r=withApi(f,()=>definedNameObserveCommand({intent:'rename_defined_name',name:'EURO_NAME',newName:'EURO_RENAMED',refersTo:'=Sheet1!$A$1',apply:true}));assert.equal(r.ok,true);assert.equal(r.state.source.present,false);assert.equal(r.state.target.name,'EURO_RENAMED')})
 await check('observer rejects rename target conflict',async()=>{const f=fixture();withApi(f,()=>definedNameObserveCommand({intent:'set_defined_name',name:'EURO_NAME',refersTo:'=Sheet1!$A$1',apply:true}));withApi(f,()=>definedNameObserveCommand({intent:'set_defined_name',name:'EURO_RENAMED',refersTo:'=Sheet1!$B$2',apply:true}));const r=withApi(f,()=>definedNameObserveCommand({intent:'rename_defined_name',name:'EURO_NAME',newName:'EURO_RENAMED',refersTo:'=Sheet1!$A$1',apply:true}));assert.equal(r.outcome,'defined-name-target-conflict')})
 await check('observer deletes and recognizes absent retry',async()=>{const f=fixture();withApi(f,()=>definedNameObserveCommand({intent:'set_defined_name',name:'EURO_NAME',refersTo:'=Sheet1!$A$1',apply:true}));const r=withApi(f,()=>definedNameObserveCommand({intent:'delete_defined_name',name:'EURO_NAME',apply:true}));assert.equal(r.ok,true);const retry=withApi(f,()=>definedNameObserveCommand({intent:'delete_defined_name',name:'EURO_NAME',apply:false}));assert.equal(retry.noOp,true)})
 await check('planner rejects ambiguous names and references',async()=>{assert.equal(agent.planTask({operations:[{intent:'set_defined_name',name:'bad name',refersTo:'=Sheet1!$A$1'}]}).ok,false);assert.equal(agent.planTask({operations:[{intent:'set_defined_name',name:'GOOD',refersTo:'Sheet1!A1'}]}).ok,false)})
 await check('executor applies then whole-verifies',async()=>{let phase=0,writes=0;const absent={ok:true,source:'live-coedit-editor',noOp:false,state:{measurable:true,present:false,name:'N',refersTo:null},verification:{measurable:true,match:false}},set={ok:true,source:'live-coedit-editor',noOp:true,state:{measurable:true,present:true,name:'N',refersTo:'=Sheet1!$A$1'},verification:{measurable:true,match:true}};const api={inspect:async()=>({ok:true,authority:'LIVE_READ'}),definedNameObserved:async(_op,apply)=>{if(apply){phase=1;writes++;return {...set,noOp:false,applied:true}}return phase?set:absent}};const r=await agent.executeDefinedNameTask({task:{operations:[{intent:'set_defined_name',name:'N',refersTo:'=Sheet1!$A$1'}]},api});assert.equal(r.ok,true);assert.equal(r.authority,'LIVE_VERIFY');assert.equal(writes,1)})
 console.log(failed?'XLSX DEFINED NAME STATIC: FAIL':'XLSX DEFINED NAME STATIC: PASS');process.exitCode=failed?1:0
})()
