'use strict'
const {openMinimalXlsxSession}=require('./xlsx-minimal-editor-session.cjs')
const {readRangeInFrame}=require('./range-reader.cjs')

async function vaultPass(){const {getSecret}=await import(process.env.MARVEEN_VAULT_MODULE||'/home/user/marveen/dist/web/vault.js');const v=getSecret(process.env.EURO_NC_PASS_VAULT_ID||'Elliot_nc_pass','xlsx-formula-setter-live-probe');if(!v)throw new Error('Elliot Nextcloud credential not found in Marveen vault');return v}
async function call(s,command,args={}){return s.frame.evaluate(({u,body,args})=>new Promise(resolve=>{const e=u==='window.editor'?window.editor:(window.Asc||{}).editor;if(!e||typeof e.callCommand!=='function')return resolve({ok:false,error:'callCommand unavailable'});let done=false;const finish=v=>{if(!done){done=true;resolve(v)}};const timer=setTimeout(()=>finish({ok:false,error:'callback timeout'}),5000);try{e.callCommand(new Function('args',body).bind(null,args),false,v=>{clearTimeout(timer);finish(v)})}catch(err){clearTimeout(timer);finish({ok:false,error:String(err&&err.message||err)})}}),{u:s.apiWhere,body:`return (${command.toString()})(args)`,args})}
function probeCommand(a){function has(o,n){return !!o&&typeof o[n]==='function'};try{var sh=Api.GetSheet(a.sheet),c=sh&&sh.GetRange(a.cell);if(!c)return {ok:false,error:'target unavailable'};var before={formula:has(c,'GetFormula')?c.GetFormula():null,value:has(c,'GetValue')?c.GetValue():null};var attempts=[];function attempt(label,fn){try{fn();attempts.push({label:label,ok:true,formula:has(c,'GetFormula')?c.GetFormula():null,value:has(c,'GetValue')?c.GetValue():null,text:has(c,'GetText')?c.GetText():null})}catch(e){attempts.push({label:label,ok:false,error:String(e&&e.message||e)})}}
if(has(c,'SetValue'))attempt('SetValue',function(){c.SetValue(a.formula)});
if('Formula' in c)attempt('property Formula',function(){c.Formula=a.formula});
if('formula' in c)attempt('property formula',function(){c.formula=a.formula});
if('Value' in c)attempt('property Value',function(){c.Value=a.formula});
if('value' in c)attempt('property value',function(){c.value=a.formula});
return {ok:true,before:before,attempts:attempts,properties:{Formula:'Formula' in c,formula:'formula' in c,Value:'Value' in c,value:'value' in c}}}catch(e){return {ok:false,error:String(e&&e.message||e)}}}
;(async()=>{const pass=await vaultPass();const s=await openMinimalXlsxSession({url:process.env.EURO_NC_URL||'https://mt-server.eu',user:process.env.EURO_NC_USER||'elliot',pass,fileId:process.env.EURO_XLSX_FILE_ID||'1231187',timeoutMs:30000,pollMs:50});try{const sheet=process.env.EURO_XLSX_TEST_SHEET||'EURO Persistent LIVE';const result=await call(s,probeCommand,{sheet,cell:'B2',formula:'=B1*2'});console.log('=== FORMULA SETTER CAPABILITY ===');console.log(JSON.stringify(result,null,2));const read=await readRangeInFrame(s.frame,s.apiWhere,{sheet,range:'B1:B2',callbackTimeoutMs:5000});console.log('=== SAME SESSION READBACK ===');console.log(JSON.stringify(read,null,2));console.log('XLSX FORMULA SETTER LIVE PROBE: PASS')}finally{await s.close()}})().catch(e=>{console.error(e&&e.stack||e);process.exitCode=1})
