'use strict'
const assert=require('assert/strict'),persistent=require('./xlsx-persistent-session.cjs')
const FILE_ID=Number(process.env.EURO_XLSX_PERSISTENT_FILE_ID||1231187)
process.env.EURO_PLAYWRIGHT_PATH=process.env.EURO_PLAYWRIGHT_PATH||'/home/user/marveen/node_modules/playwright'
function secret(id){const v=require('/home/user/marveen/dist/web/vault.js');const r=v.getSecret(id,'xlsx-print-titles-local-write-probe');if(!r)throw new Error('vault secret not found: '+id);return r}
const options={url:process.env.EURO_NEXTCLOUD_URL||'https://mt-server.eu',user:process.env.EURO_NEXTCLOUD_USER||'elliot',pass:secret('Elliot_nc_pass'),fileId:FILE_ID,timeoutMs:30000,pollMs:50}
async function inspect(api,sheet){return api.session.frame.evaluate(({where,sheet})=>new Promise(resolve=>{const e=where==='window.editor'?window.editor:(window.Asc||{}).editor;e.callCommand(new Function('var sheet='+JSON.stringify(sheet)+';try{var ss=Api.GetSheets(),a=null;for(var i=0;i<ss.length;i++)if(ss[i].GetName&&ss[i].GetName()===sheet){a=ss[i];break}var ws=a&&a.worksheet,wb=ws&&ws.workbook,d=wb&&wb.getDefinesNames?wb.getDefinesNames("Print_Titles",ws.getId(),true):null;return {ok:!!ws,id:ws&&ws.getId?ws.getId():null,local:d?{name:d.name||null,ref:d.ref||null,sheetId:d.sheetId===undefined?null:d.sheetId,localSheetId:d.localSheetId===undefined?null:d.localSheetId}:null}}catch(err){return {ok:false,error:String(err&&err.stack||err)}}'),false,resolve)}),{where:api.session.apiWhere,sheet})}
;(async()=>{const sheet='EURO PTLOCAL '+String(Date.now()).slice(-7),ref="='"+sheet.replace(/'/g,"''")+"'!$1:$2"
 const fixture=await persistent.withPersistentXlsxSession(options,async api=>{const c=await api.createSheetVerified(sheet);return c.ok?{ok:true,outcome:'fixture',authority:'LIVE_VERIFY',noOp:false}:c});assert.equal(fixture.ok,true)
 const first=await persistent.withPersistentXlsxSession(options,async api=>{const before=await inspect(api,sheet);const write=await api.session.frame.evaluate(({where,sheet,ref})=>new Promise(resolve=>{const e=where==='window.editor'?window.editor:(window.Asc||{}).editor;e.callCommand(new Function('var sheet='+JSON.stringify(sheet)+',ref='+JSON.stringify(ref)+';try{var ss=Api.GetSheets(),a=null;for(var i=0;i<ss.length;i++)if(ss[i].GetName&&ss[i].GetName()===sheet){a=ss[i];break}var ws=a&&a.worksheet,wb=ws&&ws.workbook,r=wb.addDefName("Print_Titles",ref,ws.getId(),false,false),d=wb.getDefinesNames("Print_Titles",ws.getId(),true);return {ok:!!d,returnType:typeof r,returnValue:r===undefined?null:r,local:d?{name:d.name||null,ref:d.ref||null,sheetId:d.sheetId===undefined?null:d.sheetId,localSheetId:d.localSheetId===undefined?null:d.localSheetId}:null}}catch(err){return {ok:false,error:String(err&&err.stack||err)}}'),false,resolve)}),{where:api.session.apiWhere,sheet,ref});if(write.ok)api.session.markWrite();return {ok:write.ok,outcome:'local-model-write-probe',authority:write.ok?'LIVE_VERIFY':'LIVE_READ',noOp:false,before,write}})
 console.log('PRINT TITLES LOCAL WRITE FIRST',JSON.stringify(first,null,2));assert.equal(first.ok,true)
 const retry=await persistent.withPersistentXlsxSession(options,async api=>{const state=await inspect(api,sheet);return {ok:true,outcome:'local-model-write-reopen',authority:'LIVE_VERIFY',noOp:true,state}})
 console.log('PRINT TITLES LOCAL WRITE REOPEN',JSON.stringify(retry,null,2));assert.equal(retry.ok,true);console.log('XLSX PRINT TITLES LOCAL WRITE PROBE: PASS')})().catch(e=>{console.error(e?.stack||e);process.exitCode=1})
