'use strict'
const assert = require('assert')
const fs = require('fs')
const { statusOf, overall } = require('./m43-runtime-acceptance.cjs')

assert.strictEqual(statusOf({ok:true,verification:{status:'PASS'}}),'PASS')
assert.strictEqual(statusOf({ok:false,verification:{status:'UNKNOWN'}}),'UNKNOWN')
assert.strictEqual(statusOf({ok:false,verification:{status:'FAIL'}}),'FAIL')
assert.strictEqual(overall([{status:'PASS'},{status:'PASS'}]),'PASS')
assert.strictEqual(overall([{status:'PASS'},{status:'UNKNOWN'}]),'UNKNOWN')
assert.strictEqual(overall([{status:'UNKNOWN'},{status:'FAIL'}]),'FAIL')

const src=fs.readFileSync('m43-runtime-acceptance.cjs','utf8')
assert.match(src,/runLayoutInFrame/)
assert.match(src,/runOperationInFrame/)
assert.match(src,/column-width/)
assert.match(src,/row-height/)
assert.match(src,/column-hide/)
assert.match(src,/column-show/)
assert.match(src,/row-hide/)
assert.match(src,/row-show/)
assert.match(src,/autofit-column/)
assert.match(src,/autofit-row/)
assert.match(src,/row-insert/)
assert.match(src,/row-delete/)
assert.match(src,/column-insert/)
assert.match(src,/column-delete/)
assert.match(src,/humanObservationRequired: true/)
assert.doesNotMatch(src,/PROPFIND|unzip|writeFile/i)
console.log('test_m43_runtime_acceptance: OK')
