'use strict'
const {withPersistentXlsxSession}=require('./xlsx-persistent-session.cjs')
const FILE_ID=Number(process.env.EURO_XLSX_PERSISTENT_FILE_ID||1231187)
process.env.EURO_PLAYWRIGHT_PATH=process.env.EURO_PLAYWRIGHT_PATH||'/home/user/marveen/node_modules/playwright'
function secret(id){const v=require('/home/user/marveen/dist/web/vault.js');const r=v.getSecret(id,'xlsx-border-internal-readback-probe');if(!r)throw new Error(`vault secret not found: ${id}`);return r}
const credentials={url:process.env.EURO_NEXTCLOUD_URL||'https://mt-server.eu',user:process.env.EURO_NEXTCLOUD_USER||'elliot',pass:secret('Elliot_nc_pass')}
function command(){
 function scalar(v){return v==null||['string','number','boolean'].includes(typeof v)?v:Object.prototype.toString.call(v)}
 function inspect(o){if(!o)return null;var out={type:Object.prototype.toString.call(o),own:{},proto:{}};try{Object.getOwnPropertyNames(o).forEach(function(n){if(/border|left|right|top|bottom|diag|style|color/i.test(n)){try{out.own[n]={type:typeof o[n],value:typeof o[n]==='function'?'[function]':scalar(o[n])}}catch(e){out.own[n]={error:String(e&&e.message||e)}}}})}catch(_){};try{var p=Object.getPrototypeOf(o);if(p)Object.getOwnPropertyNames(p).forEach(function(n){if(/border|left|right|top|bottom|diag|style|color/i.test(n)){try{out.proto[n]={type:typeof o[n],value:typeof o[n]==='function'?'[function]':scalar(o[n])}}catch(e){out.proto[n]={error:String(e&&e.message||e)}}}})}catch(_){};return out}
 function calls(o,names){var out={};names.forEach(function(n){try{if(o&&typeof o[n]==='function'){var v=o[n]();out[n]={ok:true,value:scalar(v),inspect:inspect(v)}}else out[n]={ok:false,missing:true}}catch(e){out[n]={ok:false,error:String(e&&e.message||e)}}});return out}
 var sh=Api.GetSheets()[0],ar=sh.GetRange('A1'),r=ar&&ar.range,style=r&&typeof r.getStyle==='function'?r.getStyle():null,xfs=r&&typeof r.getXfs==='function'?r.getXfs():null,borderStyle=style&&style.border,borderXfs=xfs&&xfs.border;
 return {ok:true,outcome:'border-internal-readback-probe',source:'live-coedit-editor',sheet:sh.GetName(),range:'A1',styleBorder:inspect(borderStyle),xfsBorder:inspect(borderXfs),styleBorderCalls:calls(borderStyle,['getLeft','getRight','getTop','getBottom','getDiag','GetLeft','GetRight','GetTop','GetBottom','GetDiagonal']),xfsBorderCalls:calls(borderXfs,['getLeft','getRight','getTop','getBottom','getDiag','GetLeft','GetRight','GetTop','GetBottom','GetDiagonal'])}
}
;(async()=>{const r=await withPersistentXlsxSession({url:credentials.url,user:credentials.user,pass:credentials.pass,fileId:FILE_ID,timeoutMs:30000,pollMs:50},async api=>{const body=`return (${command.toString()})();`;const x=await api.session.frame.evaluate(({u,body})=>new Promise(resolve=>{const e=u==='window.editor'?window.editor:(window.Asc||{}).editor;let done=false;const f=v=>{if(!done){done=true;resolve(v)}};try{e.callCommand(new Function(body),false,v=>f(v||{ok:false,outcome:'empty'}))}catch(err){f({ok:false,outcome:'error',error:String(err&&err.message||err)})}setTimeout(()=>f({ok:false,outcome:'timeout'}),10000)}),{u:api.session.apiWhere,body});return {...x,authority:x.ok?'LIVE_READ':'PLAN_ONLY',writeAllowed:false,noOp:true}});console.log(JSON.stringify(r,null,2));if(!r.ok)process.exitCode=1})().catch(e=>{console.error(e);process.exitCode=1})
