'use strict'
const assert=require('assert')
const {executeAgentTaskInPersistentSession}=require('./xlsx-persistent-session.cjs')
const {executeFormatTaskInPersistentSession}=require('./xlsx-persistent-format.cjs')
const FILE_ID=Number(process.env.EURO_XLSX_PERSISTENT_FILE_ID||1231187)
process.env.EURO_PLAYWRIGHT_PATH=process.env.EURO_PLAYWRIGHT_PATH||'/home/user/marveen/node_modules/playwright'
function secret(id){const v=require('/home/user/marveen/dist/web/vault.js');const r=v.getSecret(id,'xlsx-persistent-format-live-acceptance');if(!r)throw new Error(`vault secret not found: ${id}`);return r}
const credentials={url:process.env.EURO_NEXTCLOUD_URL||'https://mt-server.eu',user:process.env.EURO_NEXTCLOUD_USER||'elliot',pass:secret('Elliot_nc_pass')},common={fileId:FILE_ID,credentials,timeoutMs:30000,pollMs:50}
function diagnostic(r){return {outcome:r.outcome,authority:r.authority,noOp:r.noOp,writes:r.persistentSession?.writes,barrier:r.persistentSession?.persistenceBarrier?.ok,pre:r.pre?{ok:r.pre.ok,outcome:r.pre.outcome,noOp:r.pre.noOp,verification:r.pre.verification,beforeVerification:r.pre.beforeVerification}:undefined,applied:r.applied?{ok:r.applied.ok,outcome:r.applied.outcome,noOp:r.applied.noOp,verification:r.applied.verification,beforeVerification:r.applied.beforeVerification}:undefined,final:r.final?{ok:r.final.ok,outcome:r.final.outcome,noOp:r.final.noOp,verification:r.final.verification}:undefined,receipt:r.receipt}}
;(async()=>{const tag=String(Date.now()).slice(-7),sheet=`EURO FMT ${tag}`;const setup=await executeAgentTaskInPersistentSession({...common,task:{operations:[{intent:'create_sheet',name:sheet},{intent:'write_range',sheet,range:'A1:B2',values:[[1,2],[3,4]]}]}});assert.equal(setup.ok,true);const task={operations:[{intent:'format_range',sheet,range:'A1:B2',format:{bold:true,italic:true,fontName:'Arial',fontSize:14,alignHorizontal:'center',wrap:true,numberFormat:'0.00'}}]};const first=await executeFormatTaskInPersistentSession({...common,task});console.log('FORMAT FIRST',JSON.stringify(diagnostic(first),null,2));assert.equal(first.ok,true);assert.equal(first.authority,'LIVE_VERIFY');assert.equal(first.noOp,false);assert.equal(first.persistentSession?.writes,1);assert.equal(first.persistentSession?.persistenceBarrier?.ok,true);const retry=await executeFormatTaskInPersistentSession({...common,task});console.log('FORMAT RETRY',JSON.stringify(diagnostic(retry),null,2));assert.equal(retry.ok,true);assert.equal(retry.outcome,'xlsx-format-task-already-satisfied');assert.equal(retry.authority,'LIVE_VERIFY');assert.equal(retry.noOp,true);assert.equal(retry.persistentSession?.writes,0);assert.equal(retry.persistentSession?.persistenceBarrier,null);console.log('XLSX PERSISTENT FORMAT LIVE ACCEPTANCE: PASS')})().catch(e=>{console.error(e);process.exitCode=1})
