'use strict'
const assert=require('assert'),v=require('./xlsx-structural-range-verifier.cjs')
const read=cells=>({ok:true,authority:'LIVE_READ',cells}),x=n=>({value:n}),f=s=>({formula:s,value:0}),z=()=>({value:'',formula:null,dataType:'blank'})
let r=v.verifyRowsInsert(read([[x(1),f('=A2+B2')],[x(3),f('=A3+B3')]]),read([[z(),z()],[x(1),f('=A3+B3')],[x(3),f('=A4+B4')]]));assert.equal(r.ok,true)
r=v.verifyRowsDelete(read([[x(1),f('=A2+B2')],[x(3),f('=A3+B3')],[x(5),f('=A4+B4')]]),read([[x(3),f('=A2+B2')],[x(5),f('=A3+B3')]]));assert.equal(r.ok,true)
r=v.verifyColumnsInsert(read([[x(1),f('=B1+C1')],[x(3),f('=B2+C2')]]),read([[z(),x(1),f('=C1+D1')],[z(),x(3),f('=C2+D2')]]));assert.equal(r.ok,true)
r=v.verifyColumnsDelete(read([[x(1),x(2),x(3)],[x(4),x(5),x(6)]]),read([[x(2),x(3)],[x(5),x(6)]]));assert.equal(r.ok,true)
r=v.verifyRowsInsert(read([[x(1)]]),read([[x(9)],[x(1)]]));assert.equal(r.ok,false);assert.equal(r.outcome,'rows-insert-new-row-not-blank')
r=v.verifyColumnsDelete(read([[x(1),x(2)]]),read([[x(1)]]));assert.equal(r.ok,false);assert.equal(r.outcome,'columns-delete-shift-mismatch')
assert.equal(v.shiftFormula('=A2+$B$3+C$4+$D5',1,2),'=C3+$B$3+E$4+$D6')
console.log('XLSX STRUCTURAL RANGE VERIFIER STATIC: PASS')
