'use strict'
const {withPersistentXlsxSession}=require('./xlsx-persistent-session.cjs')
const FILE_ID=Number(process.env.EURO_XLSX_PERSISTENT_FILE_ID||1231187)
process.env.EURO_PLAYWRIGHT_PATH=process.env.EURO_PLAYWRIGHT_PATH||'/home/user/marveen/node_modules/playwright'
function secret(id){const v=require('/home/user/marveen/dist/web/vault.js');const r=v.getSecret(id,'xlsx-format-read-api-probe');if(!r)throw new Error(`vault secret not found: ${id}`);return r}
const credentials={url:process.env.EURO_NEXTCLOUD_URL||'https://mt-server.eu',user:process.env.EURO_NEXTCLOUD_USER||'elliot',pass:secret('Elliot_nc_pass')}
function probeCommand(){
 function own(obj,name){try{return {exists:name in obj,type:typeof obj[name],value:typeof obj[name]==='function'?'[function]':safe(obj[name])}}catch(e){return {exists:false,error:String(e&&e.message||e)}}}
 function safe(v){if(v==null||typeof v==='string'||typeof v==='number'||typeof v==='boolean')return v;try{if(v&&typeof v.GetRGB==='function')return {type:'color',rgb:v.GetRGB()}}catch(_){};return Object.prototype.toString.call(v)}
 function call(obj,name){try{if(!obj||typeof obj[name]!=='function')return {exists:false};var v=obj[name]();return {exists:true,ok:true,type:typeof v,value:safe(v)}}catch(e){return {exists:true,ok:false,error:String(e&&e.message||e)}}}
 function names(obj){var out=[],seen={};for(var cur=obj,depth=0;cur&&depth<6;cur=Object.getPrototypeOf(cur),depth++){try{Object.getOwnPropertyNames(cur).forEach(function(n){if(!seen[n]&&/(font|bold|italic|align|wrap|format|fill|style|textpr)/i.test(n)){seen[n]=1;out.push(n)}})}catch(_){}}return out.sort()}
 var sheets=Api.GetSheets(),sheet=sheets&&sheets.length?sheets[0]:null;if(!sheet)return {ok:false,outcome:'no-sheet',source:'live-coedit-editor'};var range=sheet.GetRange('A1');if(!range)return {ok:false,outcome:'no-range',source:'live-coedit-editor'};
 var props={},propNames=['Bold','Italic','FontName','FontSize','AlignHorizontal','AlignVertical','WrapText','NumberFormat','FontColor','FillColor'];for(var i=0;i<propNames.length;i++)props[propNames[i]]=own(range,propNames[i]);
 var getters={},getterNames=['GetBold','GetItalic','GetFontName','GetFontSize','GetAlignHorizontal','GetAlignVertical','GetWrapText','GetNumberFormat','GetFontColor','GetFillColor','GetFont','GetTextPr','GetStyle','GetFormat'];for(var j=0;j<getterNames.length;j++)getters[getterNames[j]]=call(range,getterNames[j]);
 var nested={};['GetFont','GetTextPr','GetStyle','GetFormat'].forEach(function(g){try{if(typeof range[g]==='function'){var o=range[g]();if(o){var ns=names(o),vals={};ns.slice(0,100).forEach(function(n){vals[n]=own(o,n)});nested[g]={type:Object.prototype.toString.call(o),names:ns,values:vals}}}}catch(e){nested[g]={error:String(e&&e.message||e)}}});
 return {ok:true,outcome:'read-only-format-api-probe',source:'live-coedit-editor',sheet:sheet.GetName?sheet.GetName():null,range:'A1',rangeRelevantNames:names(range),properties:props,getters:getters,nested:nested}
}
;(async()=>{const r=await withPersistentXlsxSession({url:credentials.url,user:credentials.user,pass:credentials.pass,fileId:FILE_ID,timeoutMs:30000,pollMs:50},async api=>{const body=`return (${probeCommand.toString()})();`;const result=await api.session.frame.evaluate(({u,body})=>new Promise(resolve=>{const e=u==='window.editor'?window.editor:(window.Asc||{}).editor;let done=false;const finish=v=>{if(!done){done=true;resolve(v)}};try{e.callCommand(new Function(body),false,v=>finish(v===undefined?{ok:false,outcome:'empty-callback'}:v))}catch(err){finish({ok:false,outcome:'callcommand-error',error:String(err&&err.message||err)})}setTimeout(()=>finish({ok:false,outcome:'callback-timeout'}),10000)}),{u:api.session.apiWhere,body});return {...result,authority:result?.ok?'LIVE_READ':'PLAN_ONLY',writeAllowed:false,noOp:true}});console.log(JSON.stringify(r,null,2));if(!r.ok)process.exitCode=1})().catch(e=>{console.error(e);process.exitCode=1})
