'use strict'
const assert=require('assert'),{verifyRangeCopySemantic,translateFormula}=require('./xlsx-range-copy-verifier.cjs')
const read=cells=>({ok:true,authority:'LIVE_READ',cells})
let r=verifyRangeCopySemantic(read([[{value:1},{formula:'=A1+1'}]]),read([[{value:1},{formula:'A1+1'}]]));assert.equal(r.ok,true);assert.equal(r.authority,'LIVE_VERIFY')
r=verifyRangeCopySemantic(read([[{value:1}]]),read([[{value:2}]]));assert.equal(r.ok,false);assert.equal(r.outcome,'range-copy-semantic-mismatch')
r=verifyRangeCopySemantic(read([[{value:1},{value:2}]]),read([[{value:1}]]));assert.equal(r.ok,false);assert.equal(r.outcome,'range-copy-shape-mismatch')
assert.equal(translateFormula('=A1+B$2+$C3+$D$4',0,3),'=D1+E$2+$C3+$D$4')
r=verifyRangeCopySemantic(read([[{row:2,column:2,formula:'= A1+B1'}]]),read([[{row:2,column:5,formula:'= D1+E1'}]]));assert.equal(r.ok,true);assert.equal(r.authority,'LIVE_VERIFY')
r=verifyRangeCopySemantic(read([[{row:2,column:2,formula:'=$A$1+A1'}]]),read([[{row:2,column:5,formula:'=$A$1+D1'}]]));assert.equal(r.ok,true)
r=verifyRangeCopySemantic(read([[{row:2,column:2,formula:'=A1+B1'}]]),read([[{row:2,column:5,formula:'=A1+B1'}]]));assert.equal(r.ok,false)
console.log('XLSX RANGE COPY VERIFIER STATIC: PASS')
