'use strict'
const assert=require('assert/strict')
const batch=require('./xlsx-persistent-batch.cjs')
const mcp=require('./xlsx-batch-mcp.cjs')
const {buildCrossFamilyTask,withRetryReceipts}=require('./xlsx-cross-family-agent-task.cjs')

const task=buildCrossFamilyTask('ABC1234'),plan=batch.planTask(task)
assert.equal(plan.ok,true)
assert.equal(task.operations.length,19)
assert.equal(plan.steps.length,13)
assert.equal(plan.readbacks.length,4)
const widthStep=plan.steps.find(step=>step.operation?.type==='column.width')
const autoFitStep=plan.steps.find(step=>step.operation?.type==='columns.autofit')
assert.equal(widthStep.transientSetup,true)
assert.equal(widthStep.supersededByIndex,autoFitStep.index)
const dateWrite=task.operations.find(op=>op.intent==='write_range'&&op.sheet===task.names.plan)
assert.deepEqual(dateWrite.values.slice(1).map(row=>row[2]),[null,null,null])
assert.deepEqual(dateWrite.formulas.slice(1).map(row=>row[2]),['=DATE(2026,10,5)','=DATE(2026,10,8)','=DATE(2026,10,12)'])
assert.deepEqual([...new Set(plan.steps.map(step=>step.family))],['core','structural','sort','filter','range-copy','range-move','format','layout','page-layout','print-setup','print-area','header-footer'])
for(const family of ['core','structural','sort','filter','range-copy','range-move','format','layout','page-layout','print-setup','print-area','header-footer'])assert(plan.steps.some(step=>step.family===family),`missing family: ${family}`)
const publicOperations=task.operations.map(op=>op.intent==='set_print_area'?{...op,printAreaMode:op.mode,mode:undefined}:op).map(op=>Object.fromEntries(Object.entries(op).filter(([,value])=>value!==undefined)))
assert.equal(mcp.schema.safeParse({file_id:'123',operations:publicOperations,readbacks:task.readbacks}).success,true)
assert.equal(batch.planTask({operations:mcp.normalizeOperations(publicOperations),readbacks:task.readbacks}).ok,true)
const receipt={steps:[{index:7,intent:'insert_rows',result:{retryToken:'structural-token'}},{index:11,intent:'move_range',result:{retryToken:'move-token'}},{index:14,intent:'layout_range',result:{retryToken:'autofit-token'}}]}
const retry=withRetryReceipts(task,receipt)
const acceptance=require('./test_xlsx_cross_family_agent_task_live_acceptance.cjs')
acceptance.assertRetryReceipts(task,{steps:[{index:13,intent:'layout_range',result:{}},...receipt.steps]})
assert.throws(()=>acceptance.assertRetryReceipts(task,{steps:receipt.steps.filter(step=>step.index!==14)}),/index 14/)
acceptance.assertBlank({dataType:'blank',rawValue:'',value:'',formula:null})
acceptance.assertBlank({dataType:'blank',rawValue:null,value:null,formula:null})
assert.throws(()=>acceptance.assertBlank(null))
assert.throws(()=>acceptance.assertBlank({dataType:'string',rawValue:'unexpected'}))
assert.equal(retry.operations.find(op=>op.intent==='insert_rows').retryToken,'structural-token')
assert.equal(retry.operations.find(op=>op.intent==='move_range').retryToken,'move-token')
assert.equal(retry.operations.find(op=>op.type==='columns.autofit').retryToken,'autofit-token')
assert.equal(retry.operations.find(op=>op.type==='column.width').retryToken,undefined)
assert.equal(task.operations.find(op=>op.intent==='insert_rows').retryToken,undefined)
console.log('XLSX CROSS-FAMILY AGENT TASK STATIC: PASS')
