'use strict'
const assert=require('assert')
const {executeAgentTaskInPersistentSession}=require('./xlsx-persistent-session.cjs')
const {executeConditionalFormatTaskInPersistentSession}=require('./xlsx-persistent-conditional-format.cjs')
const FILE_ID=Number(process.env.EURO_XLSX_PERSISTENT_FILE_ID||1231187)
process.env.EURO_PLAYWRIGHT_PATH=process.env.EURO_PLAYWRIGHT_PATH||'/home/user/marveen/node_modules/playwright'
function secret(id){const v=require('/home/user/marveen/dist/web/vault.js');const r=v.getSecret(id,'xlsx-persistent-conditional-format-live-acceptance');if(!r)throw new Error(`vault secret not found: ${id}`);return r}
const credentials={url:process.env.EURO_NEXTCLOUD_URL||'https://mt-server.eu',user:process.env.EURO_NEXTCLOUD_USER||'elliot',pass:secret('Elliot_nc_pass')},common={fileId:FILE_ID,credentials,timeoutMs:30000,pollMs:50}
function d(r){return {ok:r.ok,outcome:r.outcome,authority:r.authority,noOp:r.noOp,writes:r.persistentSession?.writes,barrier:r.persistentSession?.persistenceBarrier?.ok,wholeTaskVerification:r.wholeTaskVerification,receipt:r.receipt}}
;(async()=>{const tag=String(Date.now()).slice(-7),sheet=`EURO CF ${tag}`;const setup=await executeAgentTaskInPersistentSession({...common,task:{operations:[{intent:'create_sheet',name:sheet},{intent:'write_range',sheet,range:'A1:A3',values:[[5],[15],[25]]}]}});assert.equal(setup.ok,true)
const rule={type:'xlCellValue',operator:'xlGreater',formula1:'10',fillColor:[255,0,0],priority:1}
const add={operations:[{intent:'add_conditional_format',sheet,range:'A1:A3',rule}]};const first=await executeConditionalFormatTaskInPersistentSession({...common,task:add});console.log('CF ADD FIRST',JSON.stringify(d(first),null,2));assert.equal(first.ok,true);assert.equal(first.authority,'LIVE_VERIFY');assert.equal(first.noOp,false);assert.equal(first.persistentSession?.writes,1);assert.equal(first.persistentSession?.persistenceBarrier?.ok,true)
const retry=await executeConditionalFormatTaskInPersistentSession({...common,task:add});console.log('CF ADD RETRY',JSON.stringify(d(retry),null,2));assert.equal(retry.ok,true);assert.equal(retry.noOp,true);assert.equal(retry.persistentSession?.writes,0);assert.equal(retry.persistentSession?.persistenceBarrier,null)
const del={operations:[{intent:'delete_conditional_format',sheet,range:'A1:A3',rule}]};const removed=await executeConditionalFormatTaskInPersistentSession({...common,task:del});console.log('CF DELETE FIRST',JSON.stringify(d(removed),null,2));assert.equal(removed.ok,true);assert.equal(removed.authority,'LIVE_VERIFY');assert.equal(removed.noOp,false);assert.equal(removed.persistentSession?.writes,1);assert.equal(removed.persistentSession?.persistenceBarrier?.ok,true)
const removedRetry=await executeConditionalFormatTaskInPersistentSession({...common,task:del});console.log('CF DELETE RETRY',JSON.stringify(d(removedRetry),null,2));assert.equal(removedRetry.ok,true);assert.equal(removedRetry.noOp,true);assert.equal(removedRetry.persistentSession?.writes,0);assert.equal(removedRetry.persistentSession?.persistenceBarrier,null)
console.log('XLSX PERSISTENT CONDITIONAL FORMAT LIVE ACCEPTANCE: PASS')})().catch(e=>{console.error(e);process.exitCode=1})
