'use strict'
const assert=require('assert'),p=require('./xlsx-persistent-session.cjs'),ops=require('./workbook-ops.cjs')
process.env.EURO_PLAYWRIGHT_PATH=process.env.EURO_PLAYWRIGHT_PATH||'/home/user/marveen/node_modules/playwright'
const FILE_ID=Number(process.env.EURO_XLSX_PERSISTENT_FILE_ID||1231187)
function credentials(){const vault=require('/home/user/marveen/dist/web/vault.js');return {url:process.env.EURO_NEXTCLOUD_URL||'https://mt-server.eu',user:process.env.EURO_NEXTCLOUD_USER||'elliot',pass:vault.getSecret('Elliot_nc_pass','xlsx-structural-fullspan-runtime-probe')}}
function compact(read){return (read.cells||[]).map(row=>row.map(c=>c.formula||(c.rawValue??c.value??c.displayText??null)))}
async function setup(c,sheet){const grid=[[11,12,13],[21,22,23],[31,32,33],[41,42,43]],r=await p.executeAgentTaskInPersistentSession({fileId:FILE_ID,credentials:c,task:{operations:[{intent:'create_sheet',name:sheet},{intent:'write_range',sheet,range:'A1:C4',values:grid}]}});assert.equal(r.ok,true)}
async function probe(c,tag,type,range,readRange){const sheet=`EURO ${tag} ${String(Date.now()).slice(-7)}`;await setup(c,sheet);const r=await p.withPersistentXlsxSession({url:c.url,user:c.user,pass:c.pass,fileId:FILE_ID,timeoutMs:30000,pollMs:50},async api=>{const before=await api.readRange({sheet,range:readRange}),dispatched=await ops.runOperationInFrame(api.session.frame,api.session.apiWhere,{type,sheet,range});if(dispatched?.ok)api.session.markWrite();const after=await api.readRange({sheet,range:readRange});return {ok:false,outcome:'diagnostic-only-no-persist',authority:'LIVE_READ',noOp:true,case:{type,range},before:compact(before),dispatched,after:compact(after)}});console.log(JSON.stringify(r,null,2))}
;(async()=>{const c=credentials();await probe(c,'RSP','rows.insert','A2:C2','A1:C5');await probe(c,'CSP','columns.insert','B1:B4','A1:D4');console.log('XLSX STRUCTURAL FULLSPAN RUNTIME PROBE: COMPLETE')})().catch(e=>{console.error(e);process.exitCode=1})
