'use strict'
const assert=require('assert')
const {executeAgentTaskInPersistentSession}=require('./xlsx-persistent-session.cjs')
function env(name,fallback){const v=process.env[name]||fallback;if(!v)throw new Error(`${name} is required`);return v}
async function resolvePassword(){if(process.env.EURO_NC_PASS)return process.env.EURO_NC_PASS;const vaultPath=process.env.MARVEEN_VAULT_MODULE||'/home/user/marveen/dist/web/vault.js';const t=Date.now();const {getSecret}=await import(vaultPath);const pass=getSecret(process.env.EURO_NC_PASS_VAULT_ID||'Elliot_nc_pass','xlsx-persistent-applied-live-acceptance');if(!pass)throw new Error('Elliot Nextcloud credential not found in Marveen vault');console.log(`VAULT_LOOKUP_MS=${Date.now()-t}`);return pass}
const fileId=env('EURO_XLSX_FILE_ID','1231187')
const suffix=process.env.EURO_XLSX_APPLIED_SUFFIX||String(Date.now()).slice(-8)
const sheet=(process.env.EURO_XLSX_APPLIED_SHEET||`EURO Applied ${suffix}`).slice(0,31)
const stamp=`applied-${suffix}`
const task={operations:[{intent:'create_sheet',name:sheet},{intent:'write_range',sheet,range:'A1:B2',values:[[stamp,23],['formula',null]],formulas:[[null,null],[null,'=B1*4']]}]}
async function run(label,credentials){const t0=Date.now();const r=await executeAgentTaskInPersistentSession({fileId,task,credentials,timeoutMs:30000,pollMs:50});console.log(`=== ${label} ===`);console.log(JSON.stringify(r,null,2));console.log(`WALL_MS=${Date.now()-t0}`);assert.equal(r.ok,true);assert.equal(r.authority,'LIVE_VERIFY');assert.equal(r.wholeTaskVerification?.ok,true);assert.equal(r.persistentSession?.oneEditorSession,true);return r}
;(async()=>{const credentials={url:env('EURO_NC_URL','https://mt-server.eu'),user:env('EURO_NC_USER','elliot'),pass:await resolvePassword()};console.log(`FIXTURE_SHEET=${sheet}`);const first=await run('CLEAN APPLIED TASK',credentials);assert.equal(first.noOp,false);assert.deepEqual(first.receipt.map(x=>x.status),['APPLIED','APPLIED']);assert.ok(first.receipt.every(x=>x.verification==='LIVE_VERIFY'));assert.equal(first.persistentSession.writes,2);assert.equal(first.persistentSession.persistenceBarrier?.ok,true);const second=await run('SECOND IDENTICAL TASK',credentials);assert.equal(second.noOp,true);assert.ok(second.receipt.every(x=>x.status==='NO_OP_SATISFIED'));assert.equal(second.persistentSession.writes,0);assert.equal(second.persistentSession.persistenceBarrier,null);console.log('XLSX PERSISTENT APPLIED LIVE ACCEPTANCE: PASS')})().catch(e=>{console.error(e&&e.stack||e);process.exitCode=1})
