'use strict'
const assert=require('assert/strict'),batch=require('./xlsx-persistent-batch.cjs')
const FILE_ID=String(process.env.EURO_XLSX_PERSISTENT_FILE_ID||1231187)
process.env.EURO_PLAYWRIGHT_PATH=process.env.EURO_PLAYWRIGHT_PATH||'/home/user/marveen/node_modules/playwright'
function secret(id){const v=require('/home/user/marveen/dist/web/vault.js');const r=v.getSecret(id,'xlsx-print-titles-batch-live');if(!r)throw new Error('vault secret not found: '+id);return r}
const options={url:process.env.EURO_NEXTCLOUD_URL||'https://mt-server.eu',user:process.env.EURO_NEXTCLOUD_USER||'elliot',pass:secret('Elliot_nc_pass'),fileId:FILE_ID,timeoutMs:30000,pollMs:50}
;(async()=>{const name='EURO PTB '+String(Date.now()).slice(-7),values=[['Region','Q1','Q2','Q3'],['North',1,2,3],['West',4,5,6],['South',7,8,9],['East',10,11,12],['Central',13,14,15]],task={operations:[{intent:'create_sheet',name},{intent:'write_range',sheet:name,range:'A1:D6',values,formulas:Array.from({length:6},()=>Array(4).fill(null))},{intent:'set_print_titles',sheet:name,axis:'rows',from:1,to:1},{intent:'set_print_titles',sheet:name,axis:'columns',from:1,to:1}],readbacks:[{sheet:name,range:'A1:D6'}]}
 const first=await batch.executeBatchTaskInPersistentSession({...options,task});console.log('PRINT TITLES BATCH FIRST',JSON.stringify({ok:first.ok,outcome:first.outcome,authority:first.authority,noOp:first.noOp,writes:first.persistentSession?.writes,barrier:first.persistentSession?.persistenceBarrier,steps:first.steps?.map(s=>({index:s.index,intent:s.intent,outcome:s.result?.outcome,noOp:s.result?.noOp,state:s.result?.wholeTaskVerification?.state}))},null,2));assert.equal(first.ok,true);assert.equal(first.authority,'LIVE_VERIFY')
 const retry=await batch.executeBatchTaskInPersistentSession({...options,task});console.log('PRINT TITLES BATCH RETRY',JSON.stringify({ok:retry.ok,outcome:retry.outcome,authority:retry.authority,noOp:retry.noOp,writes:retry.persistentSession?.writes,barrier:retry.persistentSession?.persistenceBarrier,steps:retry.steps?.map(s=>({index:s.index,intent:s.intent,outcome:s.result?.outcome,noOp:s.result?.noOp,state:s.result?.wholeTaskVerification?.state}))},null,2));assert.equal(retry.ok,true);assert.equal(retry.noOp,true);assert.equal(retry.persistentSession?.writes,0);console.log('XLSX PRINT TITLES BATCH LIVE ACCEPTANCE: PASS')})().catch(e=>{console.error(e?.stack||e);process.exitCode=1})
