'use strict'
const assert=require('assert/strict'),persistent=require('./xlsx-persistent-session.cjs')
const FILE_ID=Number(process.env.EURO_XLSX_PERSISTENT_FILE_ID||1231187)
process.env.EURO_PLAYWRIGHT_PATH=process.env.EURO_PLAYWRIGHT_PATH||'/home/user/marveen/node_modules/playwright'
function secret(id){const v=require('/home/user/marveen/dist/web/vault.js');const r=v.getSecret(id,'xlsx-defined-name-model-probe');if(!r)throw new Error('vault secret not found: '+id);return r}
const options={url:process.env.EURO_NEXTCLOUD_URL||'https://mt-server.eu',user:process.env.EURO_NEXTCLOUD_USER||'elliot',pass:secret('Elliot_nc_pass'),fileId:FILE_ID,timeoutMs:30000,pollMs:50}
;(async()=>{const r=await persistent.withPersistentXlsxSession(options,async api=>{
 const p=await api.session.frame.evaluate(({where})=>new Promise(resolve=>{const e=where==='window.editor'?window.editor:(window.Asc||{}).editor;e.callCommand(function(){try{var a=Api.GetActiveSheet(),ws=a&&a.worksheet,wb=ws&&ws.workbook;function names(o){if(!o)return[];var n=[];try{n=Object.getOwnPropertyNames(o).concat(Object.getOwnPropertyNames(Object.getPrototypeOf(o)||{}))}catch(_){};return n.filter(function(x){return /(def|name)/i.test(x)}).filter(function(x,i,z){return z.indexOf(x)===i}).sort()}function src(o,n){try{return typeof o[n]==='function'?String(o[n]):null}catch(err){return 'ERROR:'+String(err&&err.message||err)}}var ns=names(wb),ss={};for(var i=0;i<ns.length;i++)ss[ns[i]]=src(wb,ns[i]);return {ok:!!wb,sheet:a&&a.GetName?a.GetName():null,sheetId:ws&&ws.getId?ws.getId():null,methods:ns,sources:ss}}catch(err){return {ok:false,error:String(err&&err.stack||err)}}},false,resolve)}),{where:api.session.apiWhere})
 return p&&p.ok?{ok:true,outcome:'xlsx-defined-name-model-api-probe',authority:'LIVE_VERIFY',noOp:true,probe:p}:{ok:false,outcome:'xlsx-defined-name-model-api-probe-failed',authority:'LIVE_READ',noOp:true,probe:p}
 });console.log('XLSX DEFINED NAME MODEL API PROBE',JSON.stringify(r,null,2));assert.equal(r.ok,true);assert.equal(r.persistentSession?.writes,0);console.log('XLSX DEFINED NAME MODEL API PROBE: PASS')})().catch(e=>{console.error(e?.stack||e);process.exitCode=1})
