'use strict'
const assert=require('assert')
const {executeAgentTaskInPersistentSession,withPersistentXlsxSession}=require('./xlsx-persistent-session.cjs')
const FILE_ID=Number(process.env.EURO_XLSX_PERSISTENT_FILE_ID||1231187)
process.env.EURO_PLAYWRIGHT_PATH=process.env.EURO_PLAYWRIGHT_PATH||'/home/user/marveen/node_modules/playwright'
function secret(id){const v=require('/home/user/marveen/dist/web/vault.js');const r=v.getSecret(id,'xlsx-freeze-panes-runtime-probe');if(!r)throw new Error(`vault secret not found: ${id}`);return r}
const credentials={url:process.env.EURO_NEXTCLOUD_URL||'https://mt-server.eu',user:process.env.EURO_NEXTCLOUD_USER||'elliot',pass:secret('Elliot_nc_pass')},common={fileId:FILE_ID,credentials,timeoutMs:30000,pollMs:50}
function probeCommand(sheetName){
 function has(o,n){return !!o&&typeof o[n]==='function'}
 function loc(fp){try{if(!has(fp,'GetLocation'))return {measurable:false};var r=fp.GetLocation();return {measurable:true,address:r&&has(r,'GetAddress')?String(r.GetAddress()):null}}catch(e){return {measurable:false,error:String(e&&e.message||e)}}}
 var sh=Api.GetSheet(sheetName);if(!sh||!has(sh,'GetFreezePanes'))return {ok:false,outcome:'freeze-api-unavailable',source:'live-coedit-editor'};var fp=sh.GetFreezePanes();if(!fp)return {ok:false,outcome:'freeze-object-unavailable',source:'live-coedit-editor'};var out={initial:loc(fp),methods:{FreezeRows:has(fp,'FreezeRows'),FreezeColumns:has(fp,'FreezeColumns'),FreezeAt:has(fp,'FreezeAt'),Unfreeze:has(fp,'Unfreeze'),GetLocation:has(fp,'GetLocation')}};
 if(!out.methods.Unfreeze||!out.methods.FreezeRows||!out.methods.FreezeColumns||!out.methods.FreezeAt)return {ok:false,outcome:'freeze-method-missing',source:'live-coedit-editor',out};
 fp.Unfreeze();out.unfrozen=loc(fp);fp.FreezeRows(2);out.rows2=loc(fp);fp.Unfreeze();fp.FreezeColumns(2);out.columns2=loc(fp);fp.Unfreeze();var r=sh.GetRange('C4');fp.FreezeAt(r);out.atC4=loc(fp);fp.Unfreeze();out.restored=loc(fp);return {ok:true,outcome:'freeze-panes-runtime-probe',source:'live-coedit-editor',sheet:sheetName,out}
}
;(async()=>{const tag=String(Date.now()).slice(-7),sheet=`EURO FRZ ${tag}`;const setup=await executeAgentTaskInPersistentSession({...common,task:{operations:[{intent:'create_sheet',name:sheet},{intent:'write_range',sheet,range:'A1:D5',values:[[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16],[17,18,19,20]]}]}});assert.equal(setup.ok,true);const r=await withPersistentXlsxSession({url:credentials.url,user:credentials.user,pass:credentials.pass,fileId:FILE_ID,timeoutMs:30000,pollMs:50},async api=>{const body=`return (${probeCommand.toString()})(${JSON.stringify(sheet)});`;const x=await api.session.frame.evaluate(({u,body})=>new Promise(resolve=>{const e=u==='window.editor'?window.editor:(window.Asc||{}).editor;let done=false;const f=v=>{if(!done){done=true;resolve(v)}};try{e.callCommand(new Function(body),false,v=>f(v||{ok:false,outcome:'empty'}))}catch(err){f({ok:false,outcome:'error',error:String(err&&err.message||err)})}setTimeout(()=>f({ok:false,outcome:'timeout'}),10000)}),{u:api.session.apiWhere,body});return {...x,authority:x.ok?'LIVE_READ':'PLAN_ONLY',writeAllowed:false,noOp:true}});console.log(JSON.stringify(r,null,2));if(!r.ok)process.exitCode=1})().catch(e=>{console.error(e);process.exitCode=1})
