'use strict'
const assert=require('assert'),p=require('./xlsx-persistent-session.cjs'),ops=require('./workbook-ops.cjs'),obs=require('./xlsx-structural-observation.cjs'),planning=require('./xlsx-agent-structural-task.cjs')
process.env.EURO_PLAYWRIGHT_PATH=process.env.EURO_PLAYWRIGHT_PATH||'/home/user/marveen/node_modules/playwright'
const FILE_ID=Number(process.env.EURO_XLSX_PERSISTENT_FILE_ID||1231187)
function credentials(){const vault=require('/home/user/marveen/dist/web/vault.js');return {url:process.env.EURO_NEXTCLOUD_URL||'https://mt-server.eu',user:process.env.EURO_NEXTCLOUD_USER||'elliot',pass:vault.getSecret('Elliot_nc_pass','xlsx-persistent-structural-formula-live-probe')}}
function compact(read){return (read.cells||[]).map(row=>row.map(c=>({v:c.rawValue??c.value??c.displayText??null,f:c.formula||null})))}
async function setup(c,sheet){const r=await p.executeAgentTaskInPersistentSession({fileId:FILE_ID,credentials:c,task:{operations:[{intent:'create_sheet',name:sheet},{intent:'write_range',sheet,range:'A1:C4',values:[[10,1,null],[20,2,null],[30,3,null],[40,4,null]],formulas:[[null,null,'=A1+B1'],[null,null,'=A2+B2'],[null,null,'=A3+B3'],[null,null,'=A4+B4']]}]}});assert.equal(r.ok,true)}
async function probe(c,tag,intent,range){const sheet=`EURO SF ${tag} ${String(Date.now()).slice(-7)}`;await setup(c,sheet);const plan=planning.planTask({operations:[{intent,sheet,range}]});assert.equal(plan.ok,true);const r=await p.withPersistentXlsxSession({url:c.url,user:c.user,pass:c.pass,fileId:FILE_ID,timeoutMs:30000,pollMs:50},async api=>{const inventory=await api.inspect(),window=obs.observation(inventory,plan.operation),before=await api.readRange({sheet,range:window.before}),dispatched=await ops.runOperationInFrame(api.session.frame,api.session.apiWhere,{type:plan.operation.type,sheet,range:window.dispatch});if(dispatched?.ok)api.session.markWrite();const after=await api.readRange({sheet,range:window.after});return {ok:false,outcome:'diagnostic-only-no-persist',authority:'LIVE_READ',noOp:true,case:{intent,requestedRange:range,dispatchRange:window.dispatch},before:compact(before),dispatched,after:compact(after)}});console.log(JSON.stringify(r,null,2))}
;(async()=>{const c=credentials();await probe(c,'RI','insert_rows','A2');await probe(c,'RD','delete_rows','A2');await probe(c,'CI','insert_columns','B1');await probe(c,'CD','delete_columns','B1');console.log('XLSX PERSISTENT STRUCTURAL FORMULA LIVE PROBE: COMPLETE')})().catch(e=>{console.error(e);process.exitCode=1})
