'use strict'
const assert=require('assert/strict'),batch=require('./xlsx-persistent-batch.cjs')
const FILE_ID=String(process.env.EURO_XLSX_PERSISTENT_FILE_ID||1231187)
process.env.EURO_PLAYWRIGHT_PATH=process.env.EURO_PLAYWRIGHT_PATH||'/home/user/marveen/node_modules/playwright'
function secret(id){const v=require('/home/user/marveen/dist/web/vault.js');const r=v.getSecret(id,'xlsx-print-area-batch-live');if(!r)throw new Error('vault secret not found: '+id);return r}
const options={url:process.env.EURO_NEXTCLOUD_URL||'https://mt-server.eu',user:process.env.EURO_NEXTCLOUD_USER||'elliot',pass:secret('Elliot_nc_pass'),fileId:FILE_ID,timeoutMs:30000,pollMs:50}
;(async()=>{const name='EURO PAB '+String(Date.now()).slice(-7),values=Array.from({length:12},(_,r)=>Array.from({length:8},(_,c)=>r*8+c+1)),task={operations:[{intent:'create_sheet',name},{intent:'write_range',sheet:name,range:'A1:H12',values,formulas:Array.from({length:12},()=>Array(8).fill(null))},{intent:'set_print_area',sheet:name,mode:'set',range:'A1:H12'}],readbacks:[{sheet:name,range:'A1:H12'}]}
 const first=await batch.executeBatchTaskInPersistentSession({...options,task});console.log('PRINT AREA BATCH FIRST',JSON.stringify({ok:first.ok,outcome:first.outcome,authority:first.authority,noOp:first.noOp,writes:first.persistentSession?.writes,barrier:first.persistentSession?.persistenceBarrier,steps:first.steps?.map(s=>({index:s.index,intent:s.intent,outcome:s.result?.outcome,noOp:s.result?.noOp,state:s.result?.wholeTaskVerification?.state}))},null,2));assert.equal(first.ok,true)
 const retry=await batch.executeBatchTaskInPersistentSession({...options,task});console.log('PRINT AREA BATCH RETRY',JSON.stringify({ok:retry.ok,outcome:retry.outcome,authority:retry.authority,noOp:retry.noOp,writes:retry.persistentSession?.writes,barrier:retry.persistentSession?.persistenceBarrier,steps:retry.steps?.map(s=>({index:s.index,intent:s.intent,outcome:s.result?.outcome,noOp:s.result?.noOp,state:s.result?.wholeTaskVerification?.state}))},null,2));assert.equal(retry.ok,true);assert.equal(retry.noOp,true);assert.equal(retry.persistentSession?.writes,0);console.log('XLSX PRINT AREA BATCH LIVE ACCEPTANCE: PASS')})().catch(e=>{console.error(e?.stack||e);process.exitCode=1})
